// Code generated by ent, DO NOT EDIT.

package scorerecord

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the scorerecord type in the database.
	Label = "score_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCompetitionID holds the string denoting the competition_id field in the database.
	FieldCompetitionID = "competition_id"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// FieldChallengeID holds the string denoting the challenge_id field in the database.
	FieldChallengeID = "challenge_id"
	// FieldRoundID holds the string denoting the round_id field in the database.
	FieldRoundID = "round_id"
	// FieldScoreType holds the string denoting the score_type field in the database.
	FieldScoreType = "score_type"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCompetition holds the string denoting the competition edge name in mutations.
	EdgeCompetition = "competition"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// EdgeChallenge holds the string denoting the challenge edge name in mutations.
	EdgeChallenge = "challenge"
	// EdgeRound holds the string denoting the round edge name in mutations.
	EdgeRound = "round"
	// Table holds the table name of the scorerecord in the database.
	Table = "score_records"
	// CompetitionTable is the table that holds the competition relation/edge.
	CompetitionTable = "score_records"
	// CompetitionInverseTable is the table name for the Competition entity.
	// It exists in this package in order to avoid circular dependency with the "competition" package.
	CompetitionInverseTable = "competitions"
	// CompetitionColumn is the table column denoting the competition relation/edge.
	CompetitionColumn = "competition_id"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "score_records"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_id"
	// ChallengeTable is the table that holds the challenge relation/edge.
	ChallengeTable = "score_records"
	// ChallengeInverseTable is the table name for the Challenge entity.
	// It exists in this package in order to avoid circular dependency with the "challenge" package.
	ChallengeInverseTable = "challenges"
	// ChallengeColumn is the table column denoting the challenge relation/edge.
	ChallengeColumn = "challenge_id"
	// RoundTable is the table that holds the round relation/edge.
	RoundTable = "score_records"
	// RoundInverseTable is the table name for the ScoringRound entity.
	// It exists in this package in order to avoid circular dependency with the "scoringround" package.
	RoundInverseTable = "scoring_rounds"
	// RoundColumn is the table column denoting the round relation/edge.
	RoundColumn = "round_id"
)

// Columns holds all SQL columns for scorerecord fields.
var Columns = []string{
	FieldID,
	FieldCompetitionID,
	FieldTeamID,
	FieldChallengeID,
	FieldRoundID,
	FieldScoreType,
	FieldPoints,
	FieldDetail,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDetail holds the default value on creation for the "detail" field.
	DefaultDetail string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// ScoreType defines the type for the "score_type" enum field.
type ScoreType string

// ScoreType values.
const (
	ScoreTypeFlagSolve   ScoreType = "flag_solve"
	ScoreTypeFirstBlood  ScoreType = "first_blood"
	ScoreTypeSecondBlood ScoreType = "second_blood"
	ScoreTypeThirdBlood  ScoreType = "third_blood"
	ScoreTypeAwdAttack   ScoreType = "awd_attack"
	ScoreTypeAwdDefense  ScoreType = "awd_defense"
	ScoreTypeAwdCheck    ScoreType = "awd_check"
	ScoreTypePenalty     ScoreType = "penalty"
	ScoreTypeHint        ScoreType = "hint"
	ScoreTypeBonus       ScoreType = "bonus"
)

func (st ScoreType) String() string {
	return string(st)
}

// ScoreTypeValidator is a validator for the "score_type" field enum values. It is called by the builders before save.
func ScoreTypeValidator(st ScoreType) error {
	switch st {
	case ScoreTypeFlagSolve, ScoreTypeFirstBlood, ScoreTypeSecondBlood, ScoreTypeThirdBlood, ScoreTypeAwdAttack, ScoreTypeAwdDefense, ScoreTypeAwdCheck, ScoreTypePenalty, ScoreTypeHint, ScoreTypeBonus:
		return nil
	default:
		return fmt.Errorf("scorerecord: invalid enum value for score_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the ScoreRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCompetitionID orders the results by the competition_id field.
func ByCompetitionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompetitionID, opts...).ToFunc()
}

// ByTeamID orders the results by the team_id field.
func ByTeamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamID, opts...).ToFunc()
}

// ByChallengeID orders the results by the challenge_id field.
func ByChallengeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChallengeID, opts...).ToFunc()
}

// ByRoundID orders the results by the round_id field.
func ByRoundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoundID, opts...).ToFunc()
}

// ByScoreType orders the results by the score_type field.
func ByScoreType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScoreType, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByDetail orders the results by the detail field.
func ByDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetail, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompetitionField orders the results by competition field.
func ByCompetitionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompetitionStep(), sql.OrderByField(field, opts...))
	}
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}

// ByChallengeField orders the results by challenge field.
func ByChallengeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChallengeStep(), sql.OrderByField(field, opts...))
	}
}

// ByRoundField orders the results by round field.
func ByRoundField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoundStep(), sql.OrderByField(field, opts...))
	}
}
func newCompetitionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompetitionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CompetitionTable, CompetitionColumn),
	)
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
	)
}
func newChallengeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChallengeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChallengeTable, ChallengeColumn),
	)
}
func newRoundStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoundInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RoundTable, RoundColumn),
	)
}
