// Code generated by ent, DO NOT EDIT.

package team

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the team type in the database.
	Label = "team"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldInviteCode holds the string denoting the invite_code field in the database.
	FieldInviteCode = "invite_code"
	// FieldCaptainID holds the string denoting the captain_id field in the database.
	FieldCaptainID = "captain_id"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCaptain holds the string denoting the captain edge name in mutations.
	EdgeCaptain = "captain"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// EdgeRegistrations holds the string denoting the registrations edge name in mutations.
	EdgeRegistrations = "registrations"
	// EdgeFlagSubmissions holds the string denoting the flag_submissions edge name in mutations.
	EdgeFlagSubmissions = "flag_submissions"
	// EdgeChallengeInstances holds the string denoting the challenge_instances edge name in mutations.
	EdgeChallengeInstances = "challenge_instances"
	// EdgeScoreRecords holds the string denoting the score_records edge name in mutations.
	EdgeScoreRecords = "score_records"
	// EdgeCheckResults holds the string denoting the check_results edge name in mutations.
	EdgeCheckResults = "check_results"
	// EdgeWriteups holds the string denoting the writeups edge name in mutations.
	EdgeWriteups = "writeups"
	// EdgeAttackReports holds the string denoting the attack_reports edge name in mutations.
	EdgeAttackReports = "attack_reports"
	// EdgeDefenseReports holds the string denoting the defense_reports edge name in mutations.
	EdgeDefenseReports = "defense_reports"
	// Table holds the table name of the team in the database.
	Table = "teams"
	// CaptainTable is the table that holds the captain relation/edge.
	CaptainTable = "teams"
	// CaptainInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CaptainInverseTable = "users"
	// CaptainColumn is the table column denoting the captain relation/edge.
	CaptainColumn = "captain_id"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "team_members"
	// MembersInverseTable is the table name for the TeamMember entity.
	// It exists in this package in order to avoid circular dependency with the "teammember" package.
	MembersInverseTable = "team_members"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "team_id"
	// RegistrationsTable is the table that holds the registrations relation/edge.
	RegistrationsTable = "team_registrations"
	// RegistrationsInverseTable is the table name for the TeamRegistration entity.
	// It exists in this package in order to avoid circular dependency with the "teamregistration" package.
	RegistrationsInverseTable = "team_registrations"
	// RegistrationsColumn is the table column denoting the registrations relation/edge.
	RegistrationsColumn = "team_id"
	// FlagSubmissionsTable is the table that holds the flag_submissions relation/edge.
	FlagSubmissionsTable = "flag_submissions"
	// FlagSubmissionsInverseTable is the table name for the FlagSubmission entity.
	// It exists in this package in order to avoid circular dependency with the "flagsubmission" package.
	FlagSubmissionsInverseTable = "flag_submissions"
	// FlagSubmissionsColumn is the table column denoting the flag_submissions relation/edge.
	FlagSubmissionsColumn = "team_id"
	// ChallengeInstancesTable is the table that holds the challenge_instances relation/edge.
	ChallengeInstancesTable = "challenge_instances"
	// ChallengeInstancesInverseTable is the table name for the ChallengeInstance entity.
	// It exists in this package in order to avoid circular dependency with the "challengeinstance" package.
	ChallengeInstancesInverseTable = "challenge_instances"
	// ChallengeInstancesColumn is the table column denoting the challenge_instances relation/edge.
	ChallengeInstancesColumn = "team_id"
	// ScoreRecordsTable is the table that holds the score_records relation/edge.
	ScoreRecordsTable = "score_records"
	// ScoreRecordsInverseTable is the table name for the ScoreRecord entity.
	// It exists in this package in order to avoid circular dependency with the "scorerecord" package.
	ScoreRecordsInverseTable = "score_records"
	// ScoreRecordsColumn is the table column denoting the score_records relation/edge.
	ScoreRecordsColumn = "team_id"
	// CheckResultsTable is the table that holds the check_results relation/edge.
	CheckResultsTable = "check_results"
	// CheckResultsInverseTable is the table name for the CheckResult entity.
	// It exists in this package in order to avoid circular dependency with the "checkresult" package.
	CheckResultsInverseTable = "check_results"
	// CheckResultsColumn is the table column denoting the check_results relation/edge.
	CheckResultsColumn = "team_id"
	// WriteupsTable is the table that holds the writeups relation/edge.
	WriteupsTable = "writeups"
	// WriteupsInverseTable is the table name for the Writeup entity.
	// It exists in this package in order to avoid circular dependency with the "writeup" package.
	WriteupsInverseTable = "writeups"
	// WriteupsColumn is the table column denoting the writeups relation/edge.
	WriteupsColumn = "team_id"
	// AttackReportsTable is the table that holds the attack_reports relation/edge.
	AttackReportsTable = "attack_reports"
	// AttackReportsInverseTable is the table name for the AttackReport entity.
	// It exists in this package in order to avoid circular dependency with the "attackreport" package.
	AttackReportsInverseTable = "attack_reports"
	// AttackReportsColumn is the table column denoting the attack_reports relation/edge.
	AttackReportsColumn = "team_id"
	// DefenseReportsTable is the table that holds the defense_reports relation/edge.
	DefenseReportsTable = "defense_reports"
	// DefenseReportsInverseTable is the table name for the DefenseReport entity.
	// It exists in this package in order to avoid circular dependency with the "defensereport" package.
	DefenseReportsInverseTable = "defense_reports"
	// DefenseReportsColumn is the table column denoting the defense_reports relation/edge.
	DefenseReportsColumn = "team_id"
)

// Columns holds all SQL columns for team fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldAvatarURL,
	FieldInviteCode,
	FieldCaptainID,
	FieldIsActive,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultAvatarURL holds the default value on creation for the "avatar_url" field.
	DefaultAvatarURL string
	// InviteCodeValidator is a validator for the "invite_code" field. It is called by the builders before save.
	InviteCodeValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Team queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByInviteCode orders the results by the invite_code field.
func ByInviteCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteCode, opts...).ToFunc()
}

// ByCaptainID orders the results by the captain_id field.
func ByCaptainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaptainID, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCaptainField orders the results by captain field.
func ByCaptainField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCaptainStep(), sql.OrderByField(field, opts...))
	}
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRegistrationsCount orders the results by registrations count.
func ByRegistrationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRegistrationsStep(), opts...)
	}
}

// ByRegistrations orders the results by registrations terms.
func ByRegistrations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRegistrationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFlagSubmissionsCount orders the results by flag_submissions count.
func ByFlagSubmissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFlagSubmissionsStep(), opts...)
	}
}

// ByFlagSubmissions orders the results by flag_submissions terms.
func ByFlagSubmissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlagSubmissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChallengeInstancesCount orders the results by challenge_instances count.
func ByChallengeInstancesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChallengeInstancesStep(), opts...)
	}
}

// ByChallengeInstances orders the results by challenge_instances terms.
func ByChallengeInstances(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChallengeInstancesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByScoreRecordsCount orders the results by score_records count.
func ByScoreRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newScoreRecordsStep(), opts...)
	}
}

// ByScoreRecords orders the results by score_records terms.
func ByScoreRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScoreRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCheckResultsCount orders the results by check_results count.
func ByCheckResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCheckResultsStep(), opts...)
	}
}

// ByCheckResults orders the results by check_results terms.
func ByCheckResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWriteupsCount orders the results by writeups count.
func ByWriteupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWriteupsStep(), opts...)
	}
}

// ByWriteups orders the results by writeups terms.
func ByWriteups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWriteupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAttackReportsCount orders the results by attack_reports count.
func ByAttackReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttackReportsStep(), opts...)
	}
}

// ByAttackReports orders the results by attack_reports terms.
func ByAttackReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttackReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDefenseReportsCount orders the results by defense_reports count.
func ByDefenseReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDefenseReportsStep(), opts...)
	}
}

// ByDefenseReports orders the results by defense_reports terms.
func ByDefenseReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDefenseReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCaptainStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CaptainInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CaptainTable, CaptainColumn),
	)
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
	)
}
func newRegistrationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RegistrationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RegistrationsTable, RegistrationsColumn),
	)
}
func newFlagSubmissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlagSubmissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FlagSubmissionsTable, FlagSubmissionsColumn),
	)
}
func newChallengeInstancesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChallengeInstancesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChallengeInstancesTable, ChallengeInstancesColumn),
	)
}
func newScoreRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScoreRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ScoreRecordsTable, ScoreRecordsColumn),
	)
}
func newCheckResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CheckResultsTable, CheckResultsColumn),
	)
}
func newWriteupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WriteupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WriteupsTable, WriteupsColumn),
	)
}
func newAttackReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttackReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttackReportsTable, AttackReportsColumn),
	)
}
func newDefenseReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DefenseReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DefenseReportsTable, DefenseReportsColumn),
	)
}
