// Code generated by ent, DO NOT EDIT.

package scoringround

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the scoringround type in the database.
	Label = "scoring_round"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCompetitionID holds the string denoting the competition_id field in the database.
	FieldCompetitionID = "competition_id"
	// FieldRoundNumber holds the string denoting the round_number field in the database.
	FieldRoundNumber = "round_number"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCompetition holds the string denoting the competition edge name in mutations.
	EdgeCompetition = "competition"
	// EdgeScoreRecords holds the string denoting the score_records edge name in mutations.
	EdgeScoreRecords = "score_records"
	// EdgeCheckResults holds the string denoting the check_results edge name in mutations.
	EdgeCheckResults = "check_results"
	// Table holds the table name of the scoringround in the database.
	Table = "scoring_rounds"
	// CompetitionTable is the table that holds the competition relation/edge.
	CompetitionTable = "scoring_rounds"
	// CompetitionInverseTable is the table name for the Competition entity.
	// It exists in this package in order to avoid circular dependency with the "competition" package.
	CompetitionInverseTable = "competitions"
	// CompetitionColumn is the table column denoting the competition relation/edge.
	CompetitionColumn = "competition_id"
	// ScoreRecordsTable is the table that holds the score_records relation/edge.
	ScoreRecordsTable = "score_records"
	// ScoreRecordsInverseTable is the table name for the ScoreRecord entity.
	// It exists in this package in order to avoid circular dependency with the "scorerecord" package.
	ScoreRecordsInverseTable = "score_records"
	// ScoreRecordsColumn is the table column denoting the score_records relation/edge.
	ScoreRecordsColumn = "round_id"
	// CheckResultsTable is the table that holds the check_results relation/edge.
	CheckResultsTable = "check_results"
	// CheckResultsInverseTable is the table name for the CheckResult entity.
	// It exists in this package in order to avoid circular dependency with the "checkresult" package.
	CheckResultsInverseTable = "check_results"
	// CheckResultsColumn is the table column denoting the check_results relation/edge.
	CheckResultsColumn = "round_id"
)

// Columns holds all SQL columns for scoringround fields.
var Columns = []string{
	FieldID,
	FieldCompetitionID,
	FieldRoundNumber,
	FieldStartedAt,
	FieldEndedAt,
	FieldStatus,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusRunning   Status = "running"
	StatusCompleted Status = "completed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusRunning, StatusCompleted:
		return nil
	default:
		return fmt.Errorf("scoringround: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ScoringRound queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCompetitionID orders the results by the competition_id field.
func ByCompetitionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompetitionID, opts...).ToFunc()
}

// ByRoundNumber orders the results by the round_number field.
func ByRoundNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoundNumber, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompetitionField orders the results by competition field.
func ByCompetitionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompetitionStep(), sql.OrderByField(field, opts...))
	}
}

// ByScoreRecordsCount orders the results by score_records count.
func ByScoreRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newScoreRecordsStep(), opts...)
	}
}

// ByScoreRecords orders the results by score_records terms.
func ByScoreRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScoreRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCheckResultsCount orders the results by check_results count.
func ByCheckResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCheckResultsStep(), opts...)
	}
}

// ByCheckResults orders the results by check_results terms.
func ByCheckResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCompetitionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompetitionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CompetitionTable, CompetitionColumn),
	)
}
func newScoreRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScoreRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ScoreRecordsTable, ScoreRecordsColumn),
	)
}
func newCheckResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CheckResultsTable, CheckResultsColumn),
	)
}
