// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/aiconfig"
)

// AiConfigCreate is the builder for creating a AiConfig entity.
type AiConfigCreate struct {
	config
	mutation *AiConfigMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *AiConfigCreate) SetProvider(v string) *AiConfigCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AiConfigCreate) SetNillableProvider(v *string) *AiConfigCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" field.
func (_c *AiConfigCreate) SetAPIKey(v string) *AiConfigCreate {
	_c.mutation.SetAPIKey(v)
	return _c
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_c *AiConfigCreate) SetNillableAPIKey(v *string) *AiConfigCreate {
	if v != nil {
		_c.SetAPIKey(*v)
	}
	return _c
}

// SetAPIBase sets the "api_base" field.
func (_c *AiConfigCreate) SetAPIBase(v string) *AiConfigCreate {
	_c.mutation.SetAPIBase(v)
	return _c
}

// SetNillableAPIBase sets the "api_base" field if the given value is not nil.
func (_c *AiConfigCreate) SetNillableAPIBase(v *string) *AiConfigCreate {
	if v != nil {
		_c.SetAPIBase(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *AiConfigCreate) SetModel(v string) *AiConfigCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AiConfigCreate) SetNillableModel(v *string) *AiConfigCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetMaxTokens sets the "max_tokens" field.
func (_c *AiConfigCreate) SetMaxTokens(v int) *AiConfigCreate {
	_c.mutation.SetMaxTokens(v)
	return _c
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_c *AiConfigCreate) SetNillableMaxTokens(v *int) *AiConfigCreate {
	if v != nil {
		_c.SetMaxTokens(*v)
	}
	return _c
}

// SetTemperature sets the "temperature" field.
func (_c *AiConfigCreate) SetTemperature(v float64) *AiConfigCreate {
	_c.mutation.SetTemperature(v)
	return _c
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_c *AiConfigCreate) SetNillableTemperature(v *float64) *AiConfigCreate {
	if v != nil {
		_c.SetTemperature(*v)
	}
	return _c
}

// SetSystemPrompt sets the "system_prompt" field.
func (_c *AiConfigCreate) SetSystemPrompt(v string) *AiConfigCreate {
	_c.mutation.SetSystemPrompt(v)
	return _c
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_c *AiConfigCreate) SetNillableSystemPrompt(v *string) *AiConfigCreate {
	if v != nil {
		_c.SetSystemPrompt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AiConfigCreate) SetUpdatedAt(v time.Time) *AiConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AiConfigCreate) SetNillableUpdatedAt(v *time.Time) *AiConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the AiConfigMutation object of the builder.
func (_c *AiConfigCreate) Mutation() *AiConfigMutation {
	return _c.mutation
}

// Save creates the AiConfig in the database.
func (_c *AiConfigCreate) Save(ctx context.Context) (*AiConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AiConfigCreate) SaveX(ctx context.Context) *AiConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AiConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AiConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AiConfigCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := aiconfig.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.APIBase(); !ok {
		v := aiconfig.DefaultAPIBase
		_c.mutation.SetAPIBase(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := aiconfig.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.MaxTokens(); !ok {
		v := aiconfig.DefaultMaxTokens
		_c.mutation.SetMaxTokens(v)
	}
	if _, ok := _c.mutation.Temperature(); !ok {
		v := aiconfig.DefaultTemperature
		_c.mutation.SetTemperature(v)
	}
	if _, ok := _c.mutation.SystemPrompt(); !ok {
		v := aiconfig.DefaultSystemPrompt
		_c.mutation.SetSystemPrompt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := aiconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AiConfigCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AiConfig.provider"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "AiConfig.model"`)}
	}
	if _, ok := _c.mutation.MaxTokens(); !ok {
		return &ValidationError{Name: "max_tokens", err: errors.New(`ent: missing required field "AiConfig.max_tokens"`)}
	}
	if _, ok := _c.mutation.Temperature(); !ok {
		return &ValidationError{Name: "temperature", err: errors.New(`ent: missing required field "AiConfig.temperature"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AiConfig.updated_at"`)}
	}
	return nil
}

func (_c *AiConfigCreate) sqlSave(ctx context.Context) (*AiConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AiConfigCreate) createSpec() (*AiConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &AiConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aiconfig.Table, sqlgraph.NewFieldSpec(aiconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(aiconfig.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.APIKey(); ok {
		_spec.SetField(aiconfig.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := _c.mutation.APIBase(); ok {
		_spec.SetField(aiconfig.FieldAPIBase, field.TypeString, value)
		_node.APIBase = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(aiconfig.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.MaxTokens(); ok {
		_spec.SetField(aiconfig.FieldMaxTokens, field.TypeInt, value)
		_node.MaxTokens = value
	}
	if value, ok := _c.mutation.Temperature(); ok {
		_spec.SetField(aiconfig.FieldTemperature, field.TypeFloat64, value)
		_node.Temperature = value
	}
	if value, ok := _c.mutation.SystemPrompt(); ok {
		_spec.SetField(aiconfig.FieldSystemPrompt, field.TypeString, value)
		_node.SystemPrompt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aiconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AiConfigCreateBulk is the builder for creating many AiConfig entities in bulk.
type AiConfigCreateBulk struct {
	config
	err      error
	builders []*AiConfigCreate
}

// Save creates the AiConfig entities in the database.
func (_c *AiConfigCreateBulk) Save(ctx context.Context) ([]*AiConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AiConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AiConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AiConfigCreateBulk) SaveX(ctx context.Context) []*AiConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AiConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AiConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
