// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ZacharyZcR/STC/backend/ent/challenge"
	"github.com/ZacharyZcR/STC/backend/ent/challengeinstance"
	"github.com/ZacharyZcR/STC/backend/ent/competition"
	"github.com/ZacharyZcR/STC/backend/ent/team"
)

// ChallengeInstance is the model entity for the ChallengeInstance schema.
type ChallengeInstance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ChallengeID holds the value of the "challenge_id" field.
	ChallengeID int `json:"challenge_id,omitempty"`
	// CompetitionID holds the value of the "competition_id" field.
	CompetitionID int `json:"competition_id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID int `json:"team_id,omitempty"`
	// ContainerID holds the value of the "container_id" field.
	ContainerID string `json:"container_id,omitempty"`
	// StackID holds the value of the "stack_id" field.
	StackID string `json:"stack_id,omitempty"`
	// StackContainers holds the value of the "stack_containers" field.
	StackContainers map[string]string `json:"stack_containers,omitempty"`
	// StackNetworks holds the value of the "stack_networks" field.
	StackNetworks map[string]string `json:"stack_networks,omitempty"`
	// Status holds the value of the "status" field.
	Status challengeinstance.Status `json:"status,omitempty"`
	// AccessURL holds the value of the "access_url" field.
	AccessURL string `json:"access_url,omitempty"`
	// Ports holds the value of the "ports" field.
	Ports map[string]string `json:"ports,omitempty"`
	// NetworkID holds the value of the "network_id" field.
	NetworkID string `json:"network_id,omitempty"`
	// Flag holds the value of the "flag" field.
	Flag string `json:"-"`
	// SSHUser holds the value of the "ssh_user" field.
	SSHUser string `json:"ssh_user,omitempty"`
	// SSHPassword holds the value of the "ssh_password" field.
	SSHPassword string `json:"-"`
	// SSHAddress holds the value of the "ssh_address" field.
	SSHAddress string `json:"ssh_address,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// StoppedAt holds the value of the "stopped_at" field.
	StoppedAt *time.Time `json:"stopped_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChallengeInstanceQuery when eager-loading is set.
	Edges        ChallengeInstanceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChallengeInstanceEdges holds the relations/edges for other nodes in the graph.
type ChallengeInstanceEdges struct {
	// Challenge holds the value of the challenge edge.
	Challenge *Challenge `json:"challenge,omitempty"`
	// Competition holds the value of the competition edge.
	Competition *Competition `json:"competition,omitempty"`
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ChallengeOrErr returns the Challenge value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChallengeInstanceEdges) ChallengeOrErr() (*Challenge, error) {
	if e.Challenge != nil {
		return e.Challenge, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: challenge.Label}
	}
	return nil, &NotLoadedError{edge: "challenge"}
}

// CompetitionOrErr returns the Competition value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChallengeInstanceEdges) CompetitionOrErr() (*Competition, error) {
	if e.Competition != nil {
		return e.Competition, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: competition.Label}
	}
	return nil, &NotLoadedError{edge: "competition"}
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChallengeInstanceEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChallengeInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case challengeinstance.FieldStackContainers, challengeinstance.FieldStackNetworks, challengeinstance.FieldPorts:
			values[i] = new([]byte)
		case challengeinstance.FieldID, challengeinstance.FieldChallengeID, challengeinstance.FieldCompetitionID, challengeinstance.FieldTeamID:
			values[i] = new(sql.NullInt64)
		case challengeinstance.FieldContainerID, challengeinstance.FieldStackID, challengeinstance.FieldStatus, challengeinstance.FieldAccessURL, challengeinstance.FieldNetworkID, challengeinstance.FieldFlag, challengeinstance.FieldSSHUser, challengeinstance.FieldSSHPassword, challengeinstance.FieldSSHAddress:
			values[i] = new(sql.NullString)
		case challengeinstance.FieldExpiresAt, challengeinstance.FieldStartedAt, challengeinstance.FieldStoppedAt, challengeinstance.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChallengeInstance fields.
func (_m *ChallengeInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case challengeinstance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case challengeinstance.FieldChallengeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field challenge_id", values[i])
			} else if value.Valid {
				_m.ChallengeID = int(value.Int64)
			}
		case challengeinstance.FieldCompetitionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field competition_id", values[i])
			} else if value.Valid {
				_m.CompetitionID = int(value.Int64)
			}
		case challengeinstance.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = int(value.Int64)
			}
		case challengeinstance.FieldContainerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field container_id", values[i])
			} else if value.Valid {
				_m.ContainerID = value.String
			}
		case challengeinstance.FieldStackID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stack_id", values[i])
			} else if value.Valid {
				_m.StackID = value.String
			}
		case challengeinstance.FieldStackContainers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field stack_containers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.StackContainers); err != nil {
					return fmt.Errorf("unmarshal field stack_containers: %w", err)
				}
			}
		case challengeinstance.FieldStackNetworks:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field stack_networks", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.StackNetworks); err != nil {
					return fmt.Errorf("unmarshal field stack_networks: %w", err)
				}
			}
		case challengeinstance.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = challengeinstance.Status(value.String)
			}
		case challengeinstance.FieldAccessURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_url", values[i])
			} else if value.Valid {
				_m.AccessURL = value.String
			}
		case challengeinstance.FieldPorts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ports", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Ports); err != nil {
					return fmt.Errorf("unmarshal field ports: %w", err)
				}
			}
		case challengeinstance.FieldNetworkID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network_id", values[i])
			} else if value.Valid {
				_m.NetworkID = value.String
			}
		case challengeinstance.FieldFlag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flag", values[i])
			} else if value.Valid {
				_m.Flag = value.String
			}
		case challengeinstance.FieldSSHUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_user", values[i])
			} else if value.Valid {
				_m.SSHUser = value.String
			}
		case challengeinstance.FieldSSHPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_password", values[i])
			} else if value.Valid {
				_m.SSHPassword = value.String
			}
		case challengeinstance.FieldSSHAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_address", values[i])
			} else if value.Valid {
				_m.SSHAddress = value.String
			}
		case challengeinstance.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case challengeinstance.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case challengeinstance.FieldStoppedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field stopped_at", values[i])
			} else if value.Valid {
				_m.StoppedAt = new(time.Time)
				*_m.StoppedAt = value.Time
			}
		case challengeinstance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChallengeInstance.
// This includes values selected through modifiers, order, etc.
func (_m *ChallengeInstance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChallenge queries the "challenge" edge of the ChallengeInstance entity.
func (_m *ChallengeInstance) QueryChallenge() *ChallengeQuery {
	return NewChallengeInstanceClient(_m.config).QueryChallenge(_m)
}

// QueryCompetition queries the "competition" edge of the ChallengeInstance entity.
func (_m *ChallengeInstance) QueryCompetition() *CompetitionQuery {
	return NewChallengeInstanceClient(_m.config).QueryCompetition(_m)
}

// QueryTeam queries the "team" edge of the ChallengeInstance entity.
func (_m *ChallengeInstance) QueryTeam() *TeamQuery {
	return NewChallengeInstanceClient(_m.config).QueryTeam(_m)
}

// Update returns a builder for updating this ChallengeInstance.
// Note that you need to call ChallengeInstance.Unwrap() before calling this method if this ChallengeInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChallengeInstance) Update() *ChallengeInstanceUpdateOne {
	return NewChallengeInstanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChallengeInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChallengeInstance) Unwrap() *ChallengeInstance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChallengeInstance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChallengeInstance) String() string {
	var builder strings.Builder
	builder.WriteString("ChallengeInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("challenge_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChallengeID))
	builder.WriteString(", ")
	builder.WriteString("competition_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompetitionID))
	builder.WriteString(", ")
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	builder.WriteString("container_id=")
	builder.WriteString(_m.ContainerID)
	builder.WriteString(", ")
	builder.WriteString("stack_id=")
	builder.WriteString(_m.StackID)
	builder.WriteString(", ")
	builder.WriteString("stack_containers=")
	builder.WriteString(fmt.Sprintf("%v", _m.StackContainers))
	builder.WriteString(", ")
	builder.WriteString("stack_networks=")
	builder.WriteString(fmt.Sprintf("%v", _m.StackNetworks))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("access_url=")
	builder.WriteString(_m.AccessURL)
	builder.WriteString(", ")
	builder.WriteString("ports=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ports))
	builder.WriteString(", ")
	builder.WriteString("network_id=")
	builder.WriteString(_m.NetworkID)
	builder.WriteString(", ")
	builder.WriteString("flag=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("ssh_user=")
	builder.WriteString(_m.SSHUser)
	builder.WriteString(", ")
	builder.WriteString("ssh_password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("ssh_address=")
	builder.WriteString(_m.SSHAddress)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StoppedAt; v != nil {
		builder.WriteString("stopped_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChallengeInstances is a parsable slice of ChallengeInstance.
type ChallengeInstances []*ChallengeInstance
