// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ZacharyZcR/STC/backend/ent/challenge"
	"github.com/ZacharyZcR/STC/backend/ent/challengehint"
)

// ChallengeHint is the model entity for the ChallengeHint schema.
type ChallengeHint struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ChallengeID holds the value of the "challenge_id" field.
	ChallengeID int `json:"challenge_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Cost holds the value of the "cost" field.
	Cost int `json:"cost,omitempty"`
	// OrderNum holds the value of the "order_num" field.
	OrderNum int `json:"order_num,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChallengeHintQuery when eager-loading is set.
	Edges        ChallengeHintEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChallengeHintEdges holds the relations/edges for other nodes in the graph.
type ChallengeHintEdges struct {
	// Challenge holds the value of the challenge edge.
	Challenge *Challenge `json:"challenge,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ChallengeOrErr returns the Challenge value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChallengeHintEdges) ChallengeOrErr() (*Challenge, error) {
	if e.Challenge != nil {
		return e.Challenge, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: challenge.Label}
	}
	return nil, &NotLoadedError{edge: "challenge"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChallengeHint) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case challengehint.FieldID, challengehint.FieldChallengeID, challengehint.FieldCost, challengehint.FieldOrderNum:
			values[i] = new(sql.NullInt64)
		case challengehint.FieldContent:
			values[i] = new(sql.NullString)
		case challengehint.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChallengeHint fields.
func (_m *ChallengeHint) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case challengehint.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case challengehint.FieldChallengeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field challenge_id", values[i])
			} else if value.Valid {
				_m.ChallengeID = int(value.Int64)
			}
		case challengehint.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case challengehint.FieldCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				_m.Cost = int(value.Int64)
			}
		case challengehint.FieldOrderNum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_num", values[i])
			} else if value.Valid {
				_m.OrderNum = int(value.Int64)
			}
		case challengehint.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChallengeHint.
// This includes values selected through modifiers, order, etc.
func (_m *ChallengeHint) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChallenge queries the "challenge" edge of the ChallengeHint entity.
func (_m *ChallengeHint) QueryChallenge() *ChallengeQuery {
	return NewChallengeHintClient(_m.config).QueryChallenge(_m)
}

// Update returns a builder for updating this ChallengeHint.
// Note that you need to call ChallengeHint.Unwrap() before calling this method if this ChallengeHint
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChallengeHint) Update() *ChallengeHintUpdateOne {
	return NewChallengeHintClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChallengeHint entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChallengeHint) Unwrap() *ChallengeHint {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChallengeHint is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChallengeHint) String() string {
	var builder strings.Builder
	builder.WriteString("ChallengeHint(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("challenge_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChallengeID))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cost))
	builder.WriteString(", ")
	builder.WriteString("order_num=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderNum))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChallengeHints is a parsable slice of ChallengeHint.
type ChallengeHints []*ChallengeHint
