// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/challenge"
	"github.com/ZacharyZcR/STC/backend/ent/checkresult"
	"github.com/ZacharyZcR/STC/backend/ent/predicate"
	"github.com/ZacharyZcR/STC/backend/ent/scoringround"
	"github.com/ZacharyZcR/STC/backend/ent/team"
)

// CheckResultUpdate is the builder for updating CheckResult entities.
type CheckResultUpdate struct {
	config
	hooks    []Hook
	mutation *CheckResultMutation
}

// Where appends a list predicates to the CheckResultUpdate builder.
func (_u *CheckResultUpdate) Where(ps ...predicate.CheckResult) *CheckResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRoundID sets the "round_id" field.
func (_u *CheckResultUpdate) SetRoundID(v int) *CheckResultUpdate {
	_u.mutation.SetRoundID(v)
	return _u
}

// SetNillableRoundID sets the "round_id" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableRoundID(v *int) *CheckResultUpdate {
	if v != nil {
		_u.SetRoundID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *CheckResultUpdate) SetTeamID(v int) *CheckResultUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableTeamID(v *int) *CheckResultUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetChallengeID sets the "challenge_id" field.
func (_u *CheckResultUpdate) SetChallengeID(v int) *CheckResultUpdate {
	_u.mutation.SetChallengeID(v)
	return _u
}

// SetNillableChallengeID sets the "challenge_id" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableChallengeID(v *int) *CheckResultUpdate {
	if v != nil {
		_u.SetChallengeID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CheckResultUpdate) SetStatus(v checkresult.Status) *CheckResultUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableStatus(v *checkresult.Status) *CheckResultUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *CheckResultUpdate) SetDetail(v string) *CheckResultUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *CheckResultUpdate) SetNillableDetail(v *string) *CheckResultUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *CheckResultUpdate) ClearDetail() *CheckResultUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// SetRound sets the "round" edge to the ScoringRound entity.
func (_u *CheckResultUpdate) SetRound(v *ScoringRound) *CheckResultUpdate {
	return _u.SetRoundID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *CheckResultUpdate) SetTeam(v *Team) *CheckResultUpdate {
	return _u.SetTeamID(v.ID)
}

// SetChallenge sets the "challenge" edge to the Challenge entity.
func (_u *CheckResultUpdate) SetChallenge(v *Challenge) *CheckResultUpdate {
	return _u.SetChallengeID(v.ID)
}

// Mutation returns the CheckResultMutation object of the builder.
func (_u *CheckResultUpdate) Mutation() *CheckResultMutation {
	return _u.mutation
}

// ClearRound clears the "round" edge to the ScoringRound entity.
func (_u *CheckResultUpdate) ClearRound() *CheckResultUpdate {
	_u.mutation.ClearRound()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *CheckResultUpdate) ClearTeam() *CheckResultUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearChallenge clears the "challenge" edge to the Challenge entity.
func (_u *CheckResultUpdate) ClearChallenge() *CheckResultUpdate {
	_u.mutation.ClearChallenge()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckResultUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := checkresult.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CheckResult.status": %w`, err)}
		}
	}
	if _u.mutation.RoundCleared() && len(_u.mutation.RoundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckResult.round"`)
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckResult.team"`)
	}
	if _u.mutation.ChallengeCleared() && len(_u.mutation.ChallengeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckResult.challenge"`)
	}
	return nil
}

func (_u *CheckResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkresult.Table, checkresult.Columns, sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(checkresult.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(checkresult.FieldDetail, field.TypeString, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(checkresult.FieldDetail, field.TypeString)
	}
	if _u.mutation.RoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.RoundTable,
			Columns: []string{checkresult.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoringround.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.RoundTable,
			Columns: []string{checkresult.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoringround.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.TeamTable,
			Columns: []string{checkresult.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.TeamTable,
			Columns: []string{checkresult.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChallengeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.ChallengeTable,
			Columns: []string{checkresult.ChallengeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(challenge.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChallengeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.ChallengeTable,
			Columns: []string{checkresult.ChallengeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(challenge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckResultUpdateOne is the builder for updating a single CheckResult entity.
type CheckResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckResultMutation
}

// SetRoundID sets the "round_id" field.
func (_u *CheckResultUpdateOne) SetRoundID(v int) *CheckResultUpdateOne {
	_u.mutation.SetRoundID(v)
	return _u
}

// SetNillableRoundID sets the "round_id" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableRoundID(v *int) *CheckResultUpdateOne {
	if v != nil {
		_u.SetRoundID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *CheckResultUpdateOne) SetTeamID(v int) *CheckResultUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableTeamID(v *int) *CheckResultUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetChallengeID sets the "challenge_id" field.
func (_u *CheckResultUpdateOne) SetChallengeID(v int) *CheckResultUpdateOne {
	_u.mutation.SetChallengeID(v)
	return _u
}

// SetNillableChallengeID sets the "challenge_id" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableChallengeID(v *int) *CheckResultUpdateOne {
	if v != nil {
		_u.SetChallengeID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CheckResultUpdateOne) SetStatus(v checkresult.Status) *CheckResultUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableStatus(v *checkresult.Status) *CheckResultUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *CheckResultUpdateOne) SetDetail(v string) *CheckResultUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *CheckResultUpdateOne) SetNillableDetail(v *string) *CheckResultUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *CheckResultUpdateOne) ClearDetail() *CheckResultUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// SetRound sets the "round" edge to the ScoringRound entity.
func (_u *CheckResultUpdateOne) SetRound(v *ScoringRound) *CheckResultUpdateOne {
	return _u.SetRoundID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *CheckResultUpdateOne) SetTeam(v *Team) *CheckResultUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetChallenge sets the "challenge" edge to the Challenge entity.
func (_u *CheckResultUpdateOne) SetChallenge(v *Challenge) *CheckResultUpdateOne {
	return _u.SetChallengeID(v.ID)
}

// Mutation returns the CheckResultMutation object of the builder.
func (_u *CheckResultUpdateOne) Mutation() *CheckResultMutation {
	return _u.mutation
}

// ClearRound clears the "round" edge to the ScoringRound entity.
func (_u *CheckResultUpdateOne) ClearRound() *CheckResultUpdateOne {
	_u.mutation.ClearRound()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *CheckResultUpdateOne) ClearTeam() *CheckResultUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearChallenge clears the "challenge" edge to the Challenge entity.
func (_u *CheckResultUpdateOne) ClearChallenge() *CheckResultUpdateOne {
	_u.mutation.ClearChallenge()
	return _u
}

// Where appends a list predicates to the CheckResultUpdate builder.
func (_u *CheckResultUpdateOne) Where(ps ...predicate.CheckResult) *CheckResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckResultUpdateOne) Select(field string, fields ...string) *CheckResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckResult entity.
func (_u *CheckResultUpdateOne) Save(ctx context.Context) (*CheckResult, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckResultUpdateOne) SaveX(ctx context.Context) *CheckResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckResultUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := checkresult.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CheckResult.status": %w`, err)}
		}
	}
	if _u.mutation.RoundCleared() && len(_u.mutation.RoundIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckResult.round"`)
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckResult.team"`)
	}
	if _u.mutation.ChallengeCleared() && len(_u.mutation.ChallengeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckResult.challenge"`)
	}
	return nil
}

func (_u *CheckResultUpdateOne) sqlSave(ctx context.Context) (_node *CheckResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkresult.Table, checkresult.Columns, sqlgraph.NewFieldSpec(checkresult.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkresult.FieldID)
		for _, f := range fields {
			if !checkresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(checkresult.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(checkresult.FieldDetail, field.TypeString, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(checkresult.FieldDetail, field.TypeString)
	}
	if _u.mutation.RoundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.RoundTable,
			Columns: []string{checkresult.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoringround.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.RoundTable,
			Columns: []string{checkresult.RoundColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoringround.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.TeamTable,
			Columns: []string{checkresult.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.TeamTable,
			Columns: []string{checkresult.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChallengeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.ChallengeTable,
			Columns: []string{checkresult.ChallengeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(challenge.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChallengeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkresult.ChallengeTable,
			Columns: []string{checkresult.ChallengeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(challenge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CheckResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
