// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ZacharyZcR/STC/backend/ent/challenge"
	"github.com/ZacharyZcR/STC/backend/ent/competition"
	"github.com/ZacharyZcR/STC/backend/ent/competitionchallenge"
)

// CompetitionChallenge is the model entity for the CompetitionChallenge schema.
type CompetitionChallenge struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CompetitionID holds the value of the "competition_id" field.
	CompetitionID int `json:"competition_id,omitempty"`
	// ChallengeID holds the value of the "challenge_id" field.
	ChallengeID int `json:"challenge_id,omitempty"`
	// OrderNum holds the value of the "order_num" field.
	OrderNum int `json:"order_num,omitempty"`
	// IsVisible holds the value of the "is_visible" field.
	IsVisible bool `json:"is_visible,omitempty"`
	// ReleasedAt holds the value of the "released_at" field.
	ReleasedAt *time.Time `json:"released_at,omitempty"`
	// ExtraScore holds the value of the "extra_score" field.
	ExtraScore int `json:"extra_score,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CompetitionChallengeQuery when eager-loading is set.
	Edges        CompetitionChallengeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CompetitionChallengeEdges holds the relations/edges for other nodes in the graph.
type CompetitionChallengeEdges struct {
	// Competition holds the value of the competition edge.
	Competition *Competition `json:"competition,omitempty"`
	// Challenge holds the value of the challenge edge.
	Challenge *Challenge `json:"challenge,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CompetitionOrErr returns the Competition value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompetitionChallengeEdges) CompetitionOrErr() (*Competition, error) {
	if e.Competition != nil {
		return e.Competition, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: competition.Label}
	}
	return nil, &NotLoadedError{edge: "competition"}
}

// ChallengeOrErr returns the Challenge value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompetitionChallengeEdges) ChallengeOrErr() (*Challenge, error) {
	if e.Challenge != nil {
		return e.Challenge, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: challenge.Label}
	}
	return nil, &NotLoadedError{edge: "challenge"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompetitionChallenge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case competitionchallenge.FieldIsVisible:
			values[i] = new(sql.NullBool)
		case competitionchallenge.FieldID, competitionchallenge.FieldCompetitionID, competitionchallenge.FieldChallengeID, competitionchallenge.FieldOrderNum, competitionchallenge.FieldExtraScore:
			values[i] = new(sql.NullInt64)
		case competitionchallenge.FieldReleasedAt, competitionchallenge.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompetitionChallenge fields.
func (_m *CompetitionChallenge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case competitionchallenge.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case competitionchallenge.FieldCompetitionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field competition_id", values[i])
			} else if value.Valid {
				_m.CompetitionID = int(value.Int64)
			}
		case competitionchallenge.FieldChallengeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field challenge_id", values[i])
			} else if value.Valid {
				_m.ChallengeID = int(value.Int64)
			}
		case competitionchallenge.FieldOrderNum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_num", values[i])
			} else if value.Valid {
				_m.OrderNum = int(value.Int64)
			}
		case competitionchallenge.FieldIsVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_visible", values[i])
			} else if value.Valid {
				_m.IsVisible = value.Bool
			}
		case competitionchallenge.FieldReleasedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field released_at", values[i])
			} else if value.Valid {
				_m.ReleasedAt = new(time.Time)
				*_m.ReleasedAt = value.Time
			}
		case competitionchallenge.FieldExtraScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field extra_score", values[i])
			} else if value.Valid {
				_m.ExtraScore = int(value.Int64)
			}
		case competitionchallenge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CompetitionChallenge.
// This includes values selected through modifiers, order, etc.
func (_m *CompetitionChallenge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCompetition queries the "competition" edge of the CompetitionChallenge entity.
func (_m *CompetitionChallenge) QueryCompetition() *CompetitionQuery {
	return NewCompetitionChallengeClient(_m.config).QueryCompetition(_m)
}

// QueryChallenge queries the "challenge" edge of the CompetitionChallenge entity.
func (_m *CompetitionChallenge) QueryChallenge() *ChallengeQuery {
	return NewCompetitionChallengeClient(_m.config).QueryChallenge(_m)
}

// Update returns a builder for updating this CompetitionChallenge.
// Note that you need to call CompetitionChallenge.Unwrap() before calling this method if this CompetitionChallenge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CompetitionChallenge) Update() *CompetitionChallengeUpdateOne {
	return NewCompetitionChallengeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CompetitionChallenge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CompetitionChallenge) Unwrap() *CompetitionChallenge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompetitionChallenge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CompetitionChallenge) String() string {
	var builder strings.Builder
	builder.WriteString("CompetitionChallenge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("competition_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompetitionID))
	builder.WriteString(", ")
	builder.WriteString("challenge_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChallengeID))
	builder.WriteString(", ")
	builder.WriteString("order_num=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderNum))
	builder.WriteString(", ")
	builder.WriteString("is_visible=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsVisible))
	builder.WriteString(", ")
	if v := _m.ReleasedAt; v != nil {
		builder.WriteString("released_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("extra_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraScore))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CompetitionChallenges is a parsable slice of CompetitionChallenge.
type CompetitionChallenges []*CompetitionChallenge
