// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/attackreport"
	"github.com/ZacharyZcR/STC/backend/ent/challengeinstance"
	"github.com/ZacharyZcR/STC/backend/ent/competition"
	"github.com/ZacharyZcR/STC/backend/ent/competitionchallenge"
	"github.com/ZacharyZcR/STC/backend/ent/defensereport"
	"github.com/ZacharyZcR/STC/backend/ent/exercisephase"
	"github.com/ZacharyZcR/STC/backend/ent/flagsubmission"
	"github.com/ZacharyZcR/STC/backend/ent/objective"
	"github.com/ZacharyZcR/STC/backend/ent/scorerecord"
	"github.com/ZacharyZcR/STC/backend/ent/scoringround"
	"github.com/ZacharyZcR/STC/backend/ent/teamregistration"
	"github.com/ZacharyZcR/STC/backend/ent/user"
	"github.com/ZacharyZcR/STC/backend/ent/writeup"
)

// CompetitionCreate is the builder for creating a Competition entity.
type CompetitionCreate struct {
	config
	mutation *CompetitionMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *CompetitionCreate) SetTitle(v string) *CompetitionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CompetitionCreate) SetDescription(v string) *CompetitionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableDescription(v *string) *CompetitionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *CompetitionCreate) SetMode(v competition.Mode) *CompetitionCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableMode(v *competition.Mode) *CompetitionCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CompetitionCreate) SetStatus(v competition.Status) *CompetitionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableStatus(v *competition.Status) *CompetitionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *CompetitionCreate) SetStartTime(v time.Time) *CompetitionCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableStartTime(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *CompetitionCreate) SetEndTime(v time.Time) *CompetitionCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableEndTime(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetRegistrationStart sets the "registration_start" field.
func (_c *CompetitionCreate) SetRegistrationStart(v time.Time) *CompetitionCreate {
	_c.mutation.SetRegistrationStart(v)
	return _c
}

// SetNillableRegistrationStart sets the "registration_start" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableRegistrationStart(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetRegistrationStart(*v)
	}
	return _c
}

// SetRegistrationEnd sets the "registration_end" field.
func (_c *CompetitionCreate) SetRegistrationEnd(v time.Time) *CompetitionCreate {
	_c.mutation.SetRegistrationEnd(v)
	return _c
}

// SetNillableRegistrationEnd sets the "registration_end" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableRegistrationEnd(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetRegistrationEnd(*v)
	}
	return _c
}

// SetMaxTeams sets the "max_teams" field.
func (_c *CompetitionCreate) SetMaxTeams(v int) *CompetitionCreate {
	_c.mutation.SetMaxTeams(v)
	return _c
}

// SetNillableMaxTeams sets the "max_teams" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableMaxTeams(v *int) *CompetitionCreate {
	if v != nil {
		_c.SetMaxTeams(*v)
	}
	return _c
}

// SetMaxTeamSize sets the "max_team_size" field.
func (_c *CompetitionCreate) SetMaxTeamSize(v int) *CompetitionCreate {
	_c.mutation.SetMaxTeamSize(v)
	return _c
}

// SetNillableMaxTeamSize sets the "max_team_size" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableMaxTeamSize(v *int) *CompetitionCreate {
	if v != nil {
		_c.SetMaxTeamSize(*v)
	}
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *CompetitionCreate) SetIsPublic(v bool) *CompetitionCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableIsPublic(v *bool) *CompetitionCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *CompetitionCreate) SetPassword(v string) *CompetitionCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillablePassword(v *string) *CompetitionCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetScoringConfig sets the "scoring_config" field.
func (_c *CompetitionCreate) SetScoringConfig(v map[string]interface{}) *CompetitionCreate {
	_c.mutation.SetScoringConfig(v)
	return _c
}

// SetBannerURL sets the "banner_url" field.
func (_c *CompetitionCreate) SetBannerURL(v string) *CompetitionCreate {
	_c.mutation.SetBannerURL(v)
	return _c
}

// SetNillableBannerURL sets the "banner_url" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableBannerURL(v *string) *CompetitionCreate {
	if v != nil {
		_c.SetBannerURL(*v)
	}
	return _c
}

// SetRules sets the "rules" field.
func (_c *CompetitionCreate) SetRules(v string) *CompetitionCreate {
	_c.mutation.SetRules(v)
	return _c
}

// SetNillableRules sets the "rules" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableRules(v *string) *CompetitionCreate {
	if v != nil {
		_c.SetRules(*v)
	}
	return _c
}

// SetScoreboardFreezeAt sets the "scoreboard_freeze_at" field.
func (_c *CompetitionCreate) SetScoreboardFreezeAt(v time.Time) *CompetitionCreate {
	_c.mutation.SetScoreboardFreezeAt(v)
	return _c
}

// SetNillableScoreboardFreezeAt sets the "scoreboard_freeze_at" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableScoreboardFreezeAt(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetScoreboardFreezeAt(*v)
	}
	return _c
}

// SetSubmitIntervalSeconds sets the "submit_interval_seconds" field.
func (_c *CompetitionCreate) SetSubmitIntervalSeconds(v int) *CompetitionCreate {
	_c.mutation.SetSubmitIntervalSeconds(v)
	return _c
}

// SetNillableSubmitIntervalSeconds sets the "submit_interval_seconds" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableSubmitIntervalSeconds(v *int) *CompetitionCreate {
	if v != nil {
		_c.SetSubmitIntervalSeconds(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *CompetitionCreate) SetCreatedBy(v int) *CompetitionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CompetitionCreate) SetCreatedAt(v time.Time) *CompetitionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableCreatedAt(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CompetitionCreate) SetUpdatedAt(v time.Time) *CompetitionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CompetitionCreate) SetNillableUpdatedAt(v *time.Time) *CompetitionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *CompetitionCreate) SetCreatorID(id int) *CompetitionCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *CompetitionCreate) SetCreator(v *User) *CompetitionCreate {
	return _c.SetCreatorID(v.ID)
}

// AddCompetitionChallengeIDs adds the "competition_challenges" edge to the CompetitionChallenge entity by IDs.
func (_c *CompetitionCreate) AddCompetitionChallengeIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddCompetitionChallengeIDs(ids...)
	return _c
}

// AddCompetitionChallenges adds the "competition_challenges" edges to the CompetitionChallenge entity.
func (_c *CompetitionCreate) AddCompetitionChallenges(v ...*CompetitionChallenge) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCompetitionChallengeIDs(ids...)
}

// AddRegistrationIDs adds the "registrations" edge to the TeamRegistration entity by IDs.
func (_c *CompetitionCreate) AddRegistrationIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddRegistrationIDs(ids...)
	return _c
}

// AddRegistrations adds the "registrations" edges to the TeamRegistration entity.
func (_c *CompetitionCreate) AddRegistrations(v ...*TeamRegistration) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRegistrationIDs(ids...)
}

// AddRoundIDs adds the "rounds" edge to the ScoringRound entity by IDs.
func (_c *CompetitionCreate) AddRoundIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddRoundIDs(ids...)
	return _c
}

// AddRounds adds the "rounds" edges to the ScoringRound entity.
func (_c *CompetitionCreate) AddRounds(v ...*ScoringRound) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoundIDs(ids...)
}

// AddFlagSubmissionIDs adds the "flag_submissions" edge to the FlagSubmission entity by IDs.
func (_c *CompetitionCreate) AddFlagSubmissionIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddFlagSubmissionIDs(ids...)
	return _c
}

// AddFlagSubmissions adds the "flag_submissions" edges to the FlagSubmission entity.
func (_c *CompetitionCreate) AddFlagSubmissions(v ...*FlagSubmission) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFlagSubmissionIDs(ids...)
}

// AddScoreRecordIDs adds the "score_records" edge to the ScoreRecord entity by IDs.
func (_c *CompetitionCreate) AddScoreRecordIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddScoreRecordIDs(ids...)
	return _c
}

// AddScoreRecords adds the "score_records" edges to the ScoreRecord entity.
func (_c *CompetitionCreate) AddScoreRecords(v ...*ScoreRecord) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddScoreRecordIDs(ids...)
}

// AddChallengeInstanceIDs adds the "challenge_instances" edge to the ChallengeInstance entity by IDs.
func (_c *CompetitionCreate) AddChallengeInstanceIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddChallengeInstanceIDs(ids...)
	return _c
}

// AddChallengeInstances adds the "challenge_instances" edges to the ChallengeInstance entity.
func (_c *CompetitionCreate) AddChallengeInstances(v ...*ChallengeInstance) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChallengeInstanceIDs(ids...)
}

// AddWriteupIDs adds the "writeups" edge to the Writeup entity by IDs.
func (_c *CompetitionCreate) AddWriteupIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddWriteupIDs(ids...)
	return _c
}

// AddWriteups adds the "writeups" edges to the Writeup entity.
func (_c *CompetitionCreate) AddWriteups(v ...*Writeup) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWriteupIDs(ids...)
}

// AddObjectiveIDs adds the "objectives" edge to the Objective entity by IDs.
func (_c *CompetitionCreate) AddObjectiveIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddObjectiveIDs(ids...)
	return _c
}

// AddObjectives adds the "objectives" edges to the Objective entity.
func (_c *CompetitionCreate) AddObjectives(v ...*Objective) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddObjectiveIDs(ids...)
}

// AddAttackReportIDs adds the "attack_reports" edge to the AttackReport entity by IDs.
func (_c *CompetitionCreate) AddAttackReportIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddAttackReportIDs(ids...)
	return _c
}

// AddAttackReports adds the "attack_reports" edges to the AttackReport entity.
func (_c *CompetitionCreate) AddAttackReports(v ...*AttackReport) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttackReportIDs(ids...)
}

// AddDefenseReportIDs adds the "defense_reports" edge to the DefenseReport entity by IDs.
func (_c *CompetitionCreate) AddDefenseReportIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddDefenseReportIDs(ids...)
	return _c
}

// AddDefenseReports adds the "defense_reports" edges to the DefenseReport entity.
func (_c *CompetitionCreate) AddDefenseReports(v ...*DefenseReport) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDefenseReportIDs(ids...)
}

// AddPhaseIDs adds the "phases" edge to the ExercisePhase entity by IDs.
func (_c *CompetitionCreate) AddPhaseIDs(ids ...int) *CompetitionCreate {
	_c.mutation.AddPhaseIDs(ids...)
	return _c
}

// AddPhases adds the "phases" edges to the ExercisePhase entity.
func (_c *CompetitionCreate) AddPhases(v ...*ExercisePhase) *CompetitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPhaseIDs(ids...)
}

// Mutation returns the CompetitionMutation object of the builder.
func (_c *CompetitionCreate) Mutation() *CompetitionMutation {
	return _c.mutation
}

// Save creates the Competition in the database.
func (_c *CompetitionCreate) Save(ctx context.Context) (*Competition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CompetitionCreate) SaveX(ctx context.Context) *Competition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompetitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompetitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CompetitionCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := competition.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := competition.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := competition.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.MaxTeams(); !ok {
		v := competition.DefaultMaxTeams
		_c.mutation.SetMaxTeams(v)
	}
	if _, ok := _c.mutation.MaxTeamSize(); !ok {
		v := competition.DefaultMaxTeamSize
		_c.mutation.SetMaxTeamSize(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := competition.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
	if _, ok := _c.mutation.Password(); !ok {
		v := competition.DefaultPassword
		_c.mutation.SetPassword(v)
	}
	if _, ok := _c.mutation.BannerURL(); !ok {
		v := competition.DefaultBannerURL
		_c.mutation.SetBannerURL(v)
	}
	if _, ok := _c.mutation.Rules(); !ok {
		v := competition.DefaultRules
		_c.mutation.SetRules(v)
	}
	if _, ok := _c.mutation.SubmitIntervalSeconds(); !ok {
		v := competition.DefaultSubmitIntervalSeconds
		_c.mutation.SetSubmitIntervalSeconds(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := competition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := competition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CompetitionCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Competition.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := competition.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Competition.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Competition.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := competition.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Competition.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Competition.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := competition.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Competition.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxTeams(); !ok {
		return &ValidationError{Name: "max_teams", err: errors.New(`ent: missing required field "Competition.max_teams"`)}
	}
	if _, ok := _c.mutation.MaxTeamSize(); !ok {
		return &ValidationError{Name: "max_team_size", err: errors.New(`ent: missing required field "Competition.max_team_size"`)}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "Competition.is_public"`)}
	}
	if _, ok := _c.mutation.SubmitIntervalSeconds(); !ok {
		return &ValidationError{Name: "submit_interval_seconds", err: errors.New(`ent: missing required field "Competition.submit_interval_seconds"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Competition.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Competition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Competition.updated_at"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Competition.creator"`)}
	}
	return nil
}

func (_c *CompetitionCreate) sqlSave(ctx context.Context) (*Competition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CompetitionCreate) createSpec() (*Competition, *sqlgraph.CreateSpec) {
	var (
		_node = &Competition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(competition.Table, sqlgraph.NewFieldSpec(competition.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(competition.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(competition.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(competition.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(competition.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(competition.FieldStartTime, field.TypeTime, value)
		_node.StartTime = &value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(competition.FieldEndTime, field.TypeTime, value)
		_node.EndTime = &value
	}
	if value, ok := _c.mutation.RegistrationStart(); ok {
		_spec.SetField(competition.FieldRegistrationStart, field.TypeTime, value)
		_node.RegistrationStart = &value
	}
	if value, ok := _c.mutation.RegistrationEnd(); ok {
		_spec.SetField(competition.FieldRegistrationEnd, field.TypeTime, value)
		_node.RegistrationEnd = &value
	}
	if value, ok := _c.mutation.MaxTeams(); ok {
		_spec.SetField(competition.FieldMaxTeams, field.TypeInt, value)
		_node.MaxTeams = value
	}
	if value, ok := _c.mutation.MaxTeamSize(); ok {
		_spec.SetField(competition.FieldMaxTeamSize, field.TypeInt, value)
		_node.MaxTeamSize = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(competition.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(competition.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.ScoringConfig(); ok {
		_spec.SetField(competition.FieldScoringConfig, field.TypeJSON, value)
		_node.ScoringConfig = value
	}
	if value, ok := _c.mutation.BannerURL(); ok {
		_spec.SetField(competition.FieldBannerURL, field.TypeString, value)
		_node.BannerURL = value
	}
	if value, ok := _c.mutation.Rules(); ok {
		_spec.SetField(competition.FieldRules, field.TypeString, value)
		_node.Rules = value
	}
	if value, ok := _c.mutation.ScoreboardFreezeAt(); ok {
		_spec.SetField(competition.FieldScoreboardFreezeAt, field.TypeTime, value)
		_node.ScoreboardFreezeAt = &value
	}
	if value, ok := _c.mutation.SubmitIntervalSeconds(); ok {
		_spec.SetField(competition.FieldSubmitIntervalSeconds, field.TypeInt, value)
		_node.SubmitIntervalSeconds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(competition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(competition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   competition.CreatorTable,
			Columns: []string{competition.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CompetitionChallengesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.CompetitionChallengesTable,
			Columns: []string{competition.CompetitionChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(competitionchallenge.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RegistrationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.RegistrationsTable,
			Columns: []string{competition.RegistrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teamregistration.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoundsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.RoundsTable,
			Columns: []string{competition.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoringround.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FlagSubmissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.FlagSubmissionsTable,
			Columns: []string{competition.FlagSubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flagsubmission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ScoreRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ScoreRecordsTable,
			Columns: []string{competition.ScoreRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scorerecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChallengeInstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ChallengeInstancesTable,
			Columns: []string{competition.ChallengeInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(challengeinstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WriteupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.WriteupsTable,
			Columns: []string{competition.WriteupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(writeup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ObjectivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.ObjectivesTable,
			Columns: []string{competition.ObjectivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objective.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttackReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.AttackReportsTable,
			Columns: []string{competition.AttackReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attackreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DefenseReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.DefenseReportsTable,
			Columns: []string{competition.DefenseReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(defensereport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   competition.PhasesTable,
			Columns: []string{competition.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exercisephase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CompetitionCreateBulk is the builder for creating many Competition entities in bulk.
type CompetitionCreateBulk struct {
	config
	err      error
	builders []*CompetitionCreate
}

// Save creates the Competition entities in the database.
func (_c *CompetitionCreateBulk) Save(ctx context.Context) ([]*Competition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Competition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CompetitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CompetitionCreateBulk) SaveX(ctx context.Context) []*Competition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompetitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompetitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
