// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/cronjob"
)

// CronJobCreate is the builder for creating a CronJob entity.
type CronJobCreate struct {
	config
	mutation *CronJobMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CronJobCreate) SetName(v string) *CronJobCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCronExpr sets the "cron_expr" field.
func (_c *CronJobCreate) SetCronExpr(v string) *CronJobCreate {
	_c.mutation.SetCronExpr(v)
	return _c
}

// SetHandler sets the "handler" field.
func (_c *CronJobCreate) SetHandler(v string) *CronJobCreate {
	_c.mutation.SetHandler(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CronJobCreate) SetEnabled(v bool) *CronJobCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableEnabled(v *bool) *CronJobCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLastRunAt sets the "last_run_at" field.
func (_c *CronJobCreate) SetLastRunAt(v time.Time) *CronJobCreate {
	_c.mutation.SetLastRunAt(v)
	return _c
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableLastRunAt(v *time.Time) *CronJobCreate {
	if v != nil {
		_c.SetLastRunAt(*v)
	}
	return _c
}

// SetLastStatus sets the "last_status" field.
func (_c *CronJobCreate) SetLastStatus(v string) *CronJobCreate {
	_c.mutation.SetLastStatus(v)
	return _c
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableLastStatus(v *string) *CronJobCreate {
	if v != nil {
		_c.SetLastStatus(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *CronJobCreate) SetLastError(v string) *CronJobCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableLastError(v *string) *CronJobCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetNextRunAt sets the "next_run_at" field.
func (_c *CronJobCreate) SetNextRunAt(v time.Time) *CronJobCreate {
	_c.mutation.SetNextRunAt(v)
	return _c
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableNextRunAt(v *time.Time) *CronJobCreate {
	if v != nil {
		_c.SetNextRunAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CronJobCreate) SetCreatedAt(v time.Time) *CronJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableCreatedAt(v *time.Time) *CronJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CronJobCreate) SetUpdatedAt(v time.Time) *CronJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CronJobCreate) SetNillableUpdatedAt(v *time.Time) *CronJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CronJobMutation object of the builder.
func (_c *CronJobCreate) Mutation() *CronJobMutation {
	return _c.mutation
}

// Save creates the CronJob in the database.
func (_c *CronJobCreate) Save(ctx context.Context) (*CronJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CronJobCreate) SaveX(ctx context.Context) *CronJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CronJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CronJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CronJobCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := cronjob.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cronjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cronjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CronJobCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CronJob.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := cronjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CronJob.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CronExpr(); !ok {
		return &ValidationError{Name: "cron_expr", err: errors.New(`ent: missing required field "CronJob.cron_expr"`)}
	}
	if v, ok := _c.mutation.CronExpr(); ok {
		if err := cronjob.CronExprValidator(v); err != nil {
			return &ValidationError{Name: "cron_expr", err: fmt.Errorf(`ent: validator failed for field "CronJob.cron_expr": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Handler(); !ok {
		return &ValidationError{Name: "handler", err: errors.New(`ent: missing required field "CronJob.handler"`)}
	}
	if v, ok := _c.mutation.Handler(); ok {
		if err := cronjob.HandlerValidator(v); err != nil {
			return &ValidationError{Name: "handler", err: fmt.Errorf(`ent: validator failed for field "CronJob.handler": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CronJob.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CronJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CronJob.updated_at"`)}
	}
	return nil
}

func (_c *CronJobCreate) sqlSave(ctx context.Context) (*CronJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CronJobCreate) createSpec() (*CronJob, *sqlgraph.CreateSpec) {
	var (
		_node = &CronJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cronjob.Table, sqlgraph.NewFieldSpec(cronjob.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(cronjob.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CronExpr(); ok {
		_spec.SetField(cronjob.FieldCronExpr, field.TypeString, value)
		_node.CronExpr = value
	}
	if value, ok := _c.mutation.Handler(); ok {
		_spec.SetField(cronjob.FieldHandler, field.TypeString, value)
		_node.Handler = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(cronjob.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LastRunAt(); ok {
		_spec.SetField(cronjob.FieldLastRunAt, field.TypeTime, value)
		_node.LastRunAt = &value
	}
	if value, ok := _c.mutation.LastStatus(); ok {
		_spec.SetField(cronjob.FieldLastStatus, field.TypeString, value)
		_node.LastStatus = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(cronjob.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.NextRunAt(); ok {
		_spec.SetField(cronjob.FieldNextRunAt, field.TypeTime, value)
		_node.NextRunAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cronjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cronjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CronJobCreateBulk is the builder for creating many CronJob entities in bulk.
type CronJobCreateBulk struct {
	config
	err      error
	builders []*CronJobCreate
}

// Save creates the CronJob entities in the database.
func (_c *CronJobCreateBulk) Save(ctx context.Context) ([]*CronJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CronJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CronJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CronJobCreateBulk) SaveX(ctx context.Context) []*CronJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CronJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CronJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
