// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/competition"
	"github.com/ZacharyZcR/STC/backend/ent/defensereport"
	"github.com/ZacharyZcR/STC/backend/ent/predicate"
	"github.com/ZacharyZcR/STC/backend/ent/team"
	"github.com/ZacharyZcR/STC/backend/ent/user"
)

// DefenseReportQuery is the builder for querying DefenseReport entities.
type DefenseReportQuery struct {
	config
	ctx             *QueryContext
	order           []defensereport.OrderOption
	inters          []Interceptor
	predicates      []predicate.DefenseReport
	withCompetition *CompetitionQuery
	withTeam        *TeamQuery
	withUser        *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DefenseReportQuery builder.
func (_q *DefenseReportQuery) Where(ps ...predicate.DefenseReport) *DefenseReportQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DefenseReportQuery) Limit(limit int) *DefenseReportQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DefenseReportQuery) Offset(offset int) *DefenseReportQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DefenseReportQuery) Unique(unique bool) *DefenseReportQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DefenseReportQuery) Order(o ...defensereport.OrderOption) *DefenseReportQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCompetition chains the current query on the "competition" edge.
func (_q *DefenseReportQuery) QueryCompetition() *CompetitionQuery {
	query := (&CompetitionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(defensereport.Table, defensereport.FieldID, selector),
			sqlgraph.To(competition.Table, competition.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, defensereport.CompetitionTable, defensereport.CompetitionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeam chains the current query on the "team" edge.
func (_q *DefenseReportQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(defensereport.Table, defensereport.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, defensereport.TeamTable, defensereport.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *DefenseReportQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(defensereport.Table, defensereport.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, defensereport.UserTable, defensereport.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DefenseReport entity from the query.
// Returns a *NotFoundError when no DefenseReport was found.
func (_q *DefenseReportQuery) First(ctx context.Context) (*DefenseReport, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{defensereport.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DefenseReportQuery) FirstX(ctx context.Context) *DefenseReport {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DefenseReport ID from the query.
// Returns a *NotFoundError when no DefenseReport ID was found.
func (_q *DefenseReportQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{defensereport.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DefenseReportQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DefenseReport entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DefenseReport entity is found.
// Returns a *NotFoundError when no DefenseReport entities are found.
func (_q *DefenseReportQuery) Only(ctx context.Context) (*DefenseReport, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{defensereport.Label}
	default:
		return nil, &NotSingularError{defensereport.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DefenseReportQuery) OnlyX(ctx context.Context) *DefenseReport {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DefenseReport ID in the query.
// Returns a *NotSingularError when more than one DefenseReport ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DefenseReportQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{defensereport.Label}
	default:
		err = &NotSingularError{defensereport.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DefenseReportQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DefenseReports.
func (_q *DefenseReportQuery) All(ctx context.Context) ([]*DefenseReport, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DefenseReport, *DefenseReportQuery]()
	return withInterceptors[[]*DefenseReport](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DefenseReportQuery) AllX(ctx context.Context) []*DefenseReport {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DefenseReport IDs.
func (_q *DefenseReportQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(defensereport.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DefenseReportQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DefenseReportQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DefenseReportQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DefenseReportQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DefenseReportQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DefenseReportQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DefenseReportQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DefenseReportQuery) Clone() *DefenseReportQuery {
	if _q == nil {
		return nil
	}
	return &DefenseReportQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]defensereport.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.DefenseReport{}, _q.predicates...),
		withCompetition: _q.withCompetition.Clone(),
		withTeam:        _q.withTeam.Clone(),
		withUser:        _q.withUser.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCompetition tells the query-builder to eager-load the nodes that are connected to
// the "competition" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DefenseReportQuery) WithCompetition(opts ...func(*CompetitionQuery)) *DefenseReportQuery {
	query := (&CompetitionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCompetition = query
	return _q
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DefenseReportQuery) WithTeam(opts ...func(*TeamQuery)) *DefenseReportQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeam = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DefenseReportQuery) WithUser(opts ...func(*UserQuery)) *DefenseReportQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompetitionID int `json:"competition_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DefenseReport.Query().
//		GroupBy(defensereport.FieldCompetitionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DefenseReportQuery) GroupBy(field string, fields ...string) *DefenseReportGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DefenseReportGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = defensereport.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompetitionID int `json:"competition_id,omitempty"`
//	}
//
//	client.DefenseReport.Query().
//		Select(defensereport.FieldCompetitionID).
//		Scan(ctx, &v)
func (_q *DefenseReportQuery) Select(fields ...string) *DefenseReportSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DefenseReportSelect{DefenseReportQuery: _q}
	sbuild.label = defensereport.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DefenseReportSelect configured with the given aggregations.
func (_q *DefenseReportQuery) Aggregate(fns ...AggregateFunc) *DefenseReportSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DefenseReportQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !defensereport.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DefenseReportQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DefenseReport, error) {
	var (
		nodes       = []*DefenseReport{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withCompetition != nil,
			_q.withTeam != nil,
			_q.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DefenseReport).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DefenseReport{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCompetition; query != nil {
		if err := _q.loadCompetition(ctx, query, nodes, nil,
			func(n *DefenseReport, e *Competition) { n.Edges.Competition = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTeam; query != nil {
		if err := _q.loadTeam(ctx, query, nodes, nil,
			func(n *DefenseReport, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *DefenseReport, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DefenseReportQuery) loadCompetition(ctx context.Context, query *CompetitionQuery, nodes []*DefenseReport, init func(*DefenseReport), assign func(*DefenseReport, *Competition)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DefenseReport)
	for i := range nodes {
		fk := nodes[i].CompetitionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(competition.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "competition_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DefenseReportQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*DefenseReport, init func(*DefenseReport), assign func(*DefenseReport, *Team)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DefenseReport)
	for i := range nodes {
		fk := nodes[i].TeamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DefenseReportQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*DefenseReport, init func(*DefenseReport), assign func(*DefenseReport, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DefenseReport)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DefenseReportQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DefenseReportQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(defensereport.Table, defensereport.Columns, sqlgraph.NewFieldSpec(defensereport.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, defensereport.FieldID)
		for i := range fields {
			if fields[i] != defensereport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCompetition != nil {
			_spec.Node.AddColumnOnce(defensereport.FieldCompetitionID)
		}
		if _q.withTeam != nil {
			_spec.Node.AddColumnOnce(defensereport.FieldTeamID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(defensereport.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DefenseReportQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(defensereport.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = defensereport.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DefenseReportGroupBy is the group-by builder for DefenseReport entities.
type DefenseReportGroupBy struct {
	selector
	build *DefenseReportQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DefenseReportGroupBy) Aggregate(fns ...AggregateFunc) *DefenseReportGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DefenseReportGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DefenseReportQuery, *DefenseReportGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DefenseReportGroupBy) sqlScan(ctx context.Context, root *DefenseReportQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DefenseReportSelect is the builder for selecting fields of DefenseReport entities.
type DefenseReportSelect struct {
	*DefenseReportQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DefenseReportSelect) Aggregate(fns ...AggregateFunc) *DefenseReportSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DefenseReportSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DefenseReportQuery, *DefenseReportSelect](ctx, _s.DefenseReportQuery, _s, _s.inters, v)
}

func (_s *DefenseReportSelect) sqlScan(ctx context.Context, root *DefenseReportQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
