// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/challenge"
	"github.com/ZacharyZcR/STC/backend/ent/competition"
	"github.com/ZacharyZcR/STC/backend/ent/flagsubmission"
	"github.com/ZacharyZcR/STC/backend/ent/predicate"
	"github.com/ZacharyZcR/STC/backend/ent/team"
	"github.com/ZacharyZcR/STC/backend/ent/user"
)

// FlagSubmissionQuery is the builder for querying FlagSubmission entities.
type FlagSubmissionQuery struct {
	config
	ctx             *QueryContext
	order           []flagsubmission.OrderOption
	inters          []Interceptor
	predicates      []predicate.FlagSubmission
	withCompetition *CompetitionQuery
	withChallenge   *ChallengeQuery
	withTeam        *TeamQuery
	withUser        *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FlagSubmissionQuery builder.
func (_q *FlagSubmissionQuery) Where(ps ...predicate.FlagSubmission) *FlagSubmissionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FlagSubmissionQuery) Limit(limit int) *FlagSubmissionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FlagSubmissionQuery) Offset(offset int) *FlagSubmissionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FlagSubmissionQuery) Unique(unique bool) *FlagSubmissionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FlagSubmissionQuery) Order(o ...flagsubmission.OrderOption) *FlagSubmissionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCompetition chains the current query on the "competition" edge.
func (_q *FlagSubmissionQuery) QueryCompetition() *CompetitionQuery {
	query := (&CompetitionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flagsubmission.Table, flagsubmission.FieldID, selector),
			sqlgraph.To(competition.Table, competition.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flagsubmission.CompetitionTable, flagsubmission.CompetitionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChallenge chains the current query on the "challenge" edge.
func (_q *FlagSubmissionQuery) QueryChallenge() *ChallengeQuery {
	query := (&ChallengeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flagsubmission.Table, flagsubmission.FieldID, selector),
			sqlgraph.To(challenge.Table, challenge.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flagsubmission.ChallengeTable, flagsubmission.ChallengeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeam chains the current query on the "team" edge.
func (_q *FlagSubmissionQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flagsubmission.Table, flagsubmission.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flagsubmission.TeamTable, flagsubmission.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *FlagSubmissionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flagsubmission.Table, flagsubmission.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flagsubmission.UserTable, flagsubmission.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FlagSubmission entity from the query.
// Returns a *NotFoundError when no FlagSubmission was found.
func (_q *FlagSubmissionQuery) First(ctx context.Context) (*FlagSubmission, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{flagsubmission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FlagSubmissionQuery) FirstX(ctx context.Context) *FlagSubmission {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FlagSubmission ID from the query.
// Returns a *NotFoundError when no FlagSubmission ID was found.
func (_q *FlagSubmissionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{flagsubmission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FlagSubmissionQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FlagSubmission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FlagSubmission entity is found.
// Returns a *NotFoundError when no FlagSubmission entities are found.
func (_q *FlagSubmissionQuery) Only(ctx context.Context) (*FlagSubmission, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{flagsubmission.Label}
	default:
		return nil, &NotSingularError{flagsubmission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FlagSubmissionQuery) OnlyX(ctx context.Context) *FlagSubmission {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FlagSubmission ID in the query.
// Returns a *NotSingularError when more than one FlagSubmission ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FlagSubmissionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{flagsubmission.Label}
	default:
		err = &NotSingularError{flagsubmission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FlagSubmissionQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FlagSubmissions.
func (_q *FlagSubmissionQuery) All(ctx context.Context) ([]*FlagSubmission, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FlagSubmission, *FlagSubmissionQuery]()
	return withInterceptors[[]*FlagSubmission](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FlagSubmissionQuery) AllX(ctx context.Context) []*FlagSubmission {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FlagSubmission IDs.
func (_q *FlagSubmissionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(flagsubmission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FlagSubmissionQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FlagSubmissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FlagSubmissionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FlagSubmissionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FlagSubmissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FlagSubmissionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FlagSubmissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FlagSubmissionQuery) Clone() *FlagSubmissionQuery {
	if _q == nil {
		return nil
	}
	return &FlagSubmissionQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]flagsubmission.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.FlagSubmission{}, _q.predicates...),
		withCompetition: _q.withCompetition.Clone(),
		withChallenge:   _q.withChallenge.Clone(),
		withTeam:        _q.withTeam.Clone(),
		withUser:        _q.withUser.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCompetition tells the query-builder to eager-load the nodes that are connected to
// the "competition" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlagSubmissionQuery) WithCompetition(opts ...func(*CompetitionQuery)) *FlagSubmissionQuery {
	query := (&CompetitionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCompetition = query
	return _q
}

// WithChallenge tells the query-builder to eager-load the nodes that are connected to
// the "challenge" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlagSubmissionQuery) WithChallenge(opts ...func(*ChallengeQuery)) *FlagSubmissionQuery {
	query := (&ChallengeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChallenge = query
	return _q
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlagSubmissionQuery) WithTeam(opts ...func(*TeamQuery)) *FlagSubmissionQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeam = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlagSubmissionQuery) WithUser(opts ...func(*UserQuery)) *FlagSubmissionQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompetitionID int `json:"competition_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FlagSubmission.Query().
//		GroupBy(flagsubmission.FieldCompetitionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FlagSubmissionQuery) GroupBy(field string, fields ...string) *FlagSubmissionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FlagSubmissionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = flagsubmission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompetitionID int `json:"competition_id,omitempty"`
//	}
//
//	client.FlagSubmission.Query().
//		Select(flagsubmission.FieldCompetitionID).
//		Scan(ctx, &v)
func (_q *FlagSubmissionQuery) Select(fields ...string) *FlagSubmissionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FlagSubmissionSelect{FlagSubmissionQuery: _q}
	sbuild.label = flagsubmission.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FlagSubmissionSelect configured with the given aggregations.
func (_q *FlagSubmissionQuery) Aggregate(fns ...AggregateFunc) *FlagSubmissionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FlagSubmissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !flagsubmission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FlagSubmissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FlagSubmission, error) {
	var (
		nodes       = []*FlagSubmission{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withCompetition != nil,
			_q.withChallenge != nil,
			_q.withTeam != nil,
			_q.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FlagSubmission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FlagSubmission{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCompetition; query != nil {
		if err := _q.loadCompetition(ctx, query, nodes, nil,
			func(n *FlagSubmission, e *Competition) { n.Edges.Competition = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChallenge; query != nil {
		if err := _q.loadChallenge(ctx, query, nodes, nil,
			func(n *FlagSubmission, e *Challenge) { n.Edges.Challenge = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTeam; query != nil {
		if err := _q.loadTeam(ctx, query, nodes, nil,
			func(n *FlagSubmission, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *FlagSubmission, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FlagSubmissionQuery) loadCompetition(ctx context.Context, query *CompetitionQuery, nodes []*FlagSubmission, init func(*FlagSubmission), assign func(*FlagSubmission, *Competition)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FlagSubmission)
	for i := range nodes {
		fk := nodes[i].CompetitionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(competition.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "competition_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FlagSubmissionQuery) loadChallenge(ctx context.Context, query *ChallengeQuery, nodes []*FlagSubmission, init func(*FlagSubmission), assign func(*FlagSubmission, *Challenge)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FlagSubmission)
	for i := range nodes {
		fk := nodes[i].ChallengeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(challenge.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "challenge_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FlagSubmissionQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*FlagSubmission, init func(*FlagSubmission), assign func(*FlagSubmission, *Team)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FlagSubmission)
	for i := range nodes {
		fk := nodes[i].TeamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FlagSubmissionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*FlagSubmission, init func(*FlagSubmission), assign func(*FlagSubmission, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FlagSubmission)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *FlagSubmissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FlagSubmissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(flagsubmission.Table, flagsubmission.Columns, sqlgraph.NewFieldSpec(flagsubmission.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flagsubmission.FieldID)
		for i := range fields {
			if fields[i] != flagsubmission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCompetition != nil {
			_spec.Node.AddColumnOnce(flagsubmission.FieldCompetitionID)
		}
		if _q.withChallenge != nil {
			_spec.Node.AddColumnOnce(flagsubmission.FieldChallengeID)
		}
		if _q.withTeam != nil {
			_spec.Node.AddColumnOnce(flagsubmission.FieldTeamID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(flagsubmission.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FlagSubmissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(flagsubmission.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = flagsubmission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FlagSubmissionGroupBy is the group-by builder for FlagSubmission entities.
type FlagSubmissionGroupBy struct {
	selector
	build *FlagSubmissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FlagSubmissionGroupBy) Aggregate(fns ...AggregateFunc) *FlagSubmissionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FlagSubmissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FlagSubmissionQuery, *FlagSubmissionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FlagSubmissionGroupBy) sqlScan(ctx context.Context, root *FlagSubmissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FlagSubmissionSelect is the builder for selecting fields of FlagSubmission entities.
type FlagSubmissionSelect struct {
	*FlagSubmissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FlagSubmissionSelect) Aggregate(fns ...AggregateFunc) *FlagSubmissionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FlagSubmissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FlagSubmissionQuery, *FlagSubmissionSelect](ctx, _s.FlagSubmissionQuery, _s, _s.inters, v)
}

func (_s *FlagSubmissionSelect) sqlScan(ctx context.Context, root *FlagSubmissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
