// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/loginlog"
	"github.com/ZacharyZcR/STC/backend/ent/predicate"
)

// LoginLogUpdate is the builder for updating LoginLog entities.
type LoginLogUpdate struct {
	config
	hooks    []Hook
	mutation *LoginLogMutation
}

// Where appends a list predicates to the LoginLogUpdate builder.
func (_u *LoginLogUpdate) Where(ps ...predicate.LoginLog) *LoginLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LoginLogUpdate) SetUserID(v int) *LoginLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableUserID(v *int) *LoginLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LoginLogUpdate) AddUserID(v int) *LoginLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *LoginLogUpdate) ClearUserID() *LoginLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *LoginLogUpdate) SetUsername(v string) *LoginLogUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableUsername(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *LoginLogUpdate) SetIP(v string) *LoginLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableIP(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *LoginLogUpdate) ClearIP() *LoginLogUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LoginLogUpdate) SetUserAgent(v string) *LoginLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableUserAgent(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LoginLogUpdate) ClearUserAgent() *LoginLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginLogUpdate) SetSuccess(v bool) *LoginLogUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableSuccess(v *bool) *LoginLogUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *LoginLogUpdate) SetFailureReason(v string) *LoginLogUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableFailureReason(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *LoginLogUpdate) ClearFailureReason() *LoginLogUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetLocation sets the "location" field.
func (_u *LoginLogUpdate) SetLocation(v string) *LoginLogUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *LoginLogUpdate) SetNillableLocation(v *string) *LoginLogUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *LoginLogUpdate) ClearLocation() *LoginLogUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// Mutation returns the LoginLogMutation object of the builder.
func (_u *LoginLogUpdate) Mutation() *LoginLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginLogUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := loginlog.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "LoginLog.username": %w`, err)}
		}
	}
	return nil
}

func (_u *LoginLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginlog.Table, loginlog.Columns, sqlgraph.NewFieldSpec(loginlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(loginlog.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(loginlog.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(loginlog.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(loginlog.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(loginlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(loginlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(loginlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(loginlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(loginlog.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(loginlog.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(loginlog.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(loginlog.FieldLocation, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginLogUpdateOne is the builder for updating a single LoginLog entity.
type LoginLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginLogMutation
}

// SetUserID sets the "user_id" field.
func (_u *LoginLogUpdateOne) SetUserID(v int) *LoginLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableUserID(v *int) *LoginLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LoginLogUpdateOne) AddUserID(v int) *LoginLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *LoginLogUpdateOne) ClearUserID() *LoginLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *LoginLogUpdateOne) SetUsername(v string) *LoginLogUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableUsername(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *LoginLogUpdateOne) SetIP(v string) *LoginLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableIP(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *LoginLogUpdateOne) ClearIP() *LoginLogUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *LoginLogUpdateOne) SetUserAgent(v string) *LoginLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableUserAgent(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *LoginLogUpdateOne) ClearUserAgent() *LoginLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginLogUpdateOne) SetSuccess(v bool) *LoginLogUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableSuccess(v *bool) *LoginLogUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *LoginLogUpdateOne) SetFailureReason(v string) *LoginLogUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableFailureReason(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *LoginLogUpdateOne) ClearFailureReason() *LoginLogUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetLocation sets the "location" field.
func (_u *LoginLogUpdateOne) SetLocation(v string) *LoginLogUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *LoginLogUpdateOne) SetNillableLocation(v *string) *LoginLogUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *LoginLogUpdateOne) ClearLocation() *LoginLogUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// Mutation returns the LoginLogMutation object of the builder.
func (_u *LoginLogUpdateOne) Mutation() *LoginLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the LoginLogUpdate builder.
func (_u *LoginLogUpdateOne) Where(ps ...predicate.LoginLog) *LoginLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginLogUpdateOne) Select(field string, fields ...string) *LoginLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginLog entity.
func (_u *LoginLogUpdateOne) Save(ctx context.Context) (*LoginLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginLogUpdateOne) SaveX(ctx context.Context) *LoginLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginLogUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := loginlog.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "LoginLog.username": %w`, err)}
		}
	}
	return nil
}

func (_u *LoginLogUpdateOne) sqlSave(ctx context.Context) (_node *LoginLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginlog.Table, loginlog.Columns, sqlgraph.NewFieldSpec(loginlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginlog.FieldID)
		for _, f := range fields {
			if !loginlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(loginlog.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(loginlog.FieldUserID, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(loginlog.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(loginlog.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(loginlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(loginlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(loginlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(loginlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(loginlog.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(loginlog.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(loginlog.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(loginlog.FieldLocation, field.TypeString)
	}
	_node = &LoginLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
