// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/objective"
	"github.com/ZacharyZcR/STC/backend/ent/predicate"
	"github.com/ZacharyZcR/STC/backend/ent/scenario"
	"github.com/ZacharyZcR/STC/backend/ent/user"
)

// ScenarioUpdate is the builder for updating Scenario entities.
type ScenarioUpdate struct {
	config
	hooks    []Hook
	mutation *ScenarioMutation
}

// Where appends a list predicates to the ScenarioUpdate builder.
func (_u *ScenarioUpdate) Where(ps ...predicate.Scenario) *ScenarioUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ScenarioUpdate) SetName(v string) *ScenarioUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableName(v *string) *ScenarioUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScenarioUpdate) SetDescription(v string) *ScenarioUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableDescription(v *string) *ScenarioUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScenarioUpdate) ClearDescription() *ScenarioUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTopology sets the "topology" field.
func (_u *ScenarioUpdate) SetTopology(v string) *ScenarioUpdate {
	_u.mutation.SetTopology(v)
	return _u
}

// SetNillableTopology sets the "topology" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableTopology(v *string) *ScenarioUpdate {
	if v != nil {
		_u.SetTopology(*v)
	}
	return _u
}

// ClearTopology clears the value of the "topology" field.
func (_u *ScenarioUpdate) ClearTopology() *ScenarioUpdate {
	_u.mutation.ClearTopology()
	return _u
}

// SetDockerCompose sets the "docker_compose" field.
func (_u *ScenarioUpdate) SetDockerCompose(v string) *ScenarioUpdate {
	_u.mutation.SetDockerCompose(v)
	return _u
}

// SetNillableDockerCompose sets the "docker_compose" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableDockerCompose(v *string) *ScenarioUpdate {
	if v != nil {
		_u.SetDockerCompose(*v)
	}
	return _u
}

// ClearDockerCompose clears the value of the "docker_compose" field.
func (_u *ScenarioUpdate) ClearDockerCompose() *ScenarioUpdate {
	_u.mutation.ClearDockerCompose()
	return _u
}

// SetNetworkConfig sets the "network_config" field.
func (_u *ScenarioUpdate) SetNetworkConfig(v map[string]interface{}) *ScenarioUpdate {
	_u.mutation.SetNetworkConfig(v)
	return _u
}

// ClearNetworkConfig clears the value of the "network_config" field.
func (_u *ScenarioUpdate) ClearNetworkConfig() *ScenarioUpdate {
	_u.mutation.ClearNetworkConfig()
	return _u
}

// SetDifficulty sets the "difficulty" field.
func (_u *ScenarioUpdate) SetDifficulty(v string) *ScenarioUpdate {
	_u.mutation.SetDifficulty(v)
	return _u
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableDifficulty(v *string) *ScenarioUpdate {
	if v != nil {
		_u.SetDifficulty(*v)
	}
	return _u
}

// ClearDifficulty clears the value of the "difficulty" field.
func (_u *ScenarioUpdate) ClearDifficulty() *ScenarioUpdate {
	_u.mutation.ClearDifficulty()
	return _u
}

// SetEstimatedDuration sets the "estimated_duration" field.
func (_u *ScenarioUpdate) SetEstimatedDuration(v int) *ScenarioUpdate {
	_u.mutation.ResetEstimatedDuration()
	_u.mutation.SetEstimatedDuration(v)
	return _u
}

// SetNillableEstimatedDuration sets the "estimated_duration" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableEstimatedDuration(v *int) *ScenarioUpdate {
	if v != nil {
		_u.SetEstimatedDuration(*v)
	}
	return _u
}

// AddEstimatedDuration adds value to the "estimated_duration" field.
func (_u *ScenarioUpdate) AddEstimatedDuration(v int) *ScenarioUpdate {
	_u.mutation.AddEstimatedDuration(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *ScenarioUpdate) SetTags(v []string) *ScenarioUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ScenarioUpdate) AppendTags(v []string) *ScenarioUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ScenarioUpdate) ClearTags() *ScenarioUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ScenarioUpdate) SetCreatedBy(v int) *ScenarioUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ScenarioUpdate) SetNillableCreatedBy(v *int) *ScenarioUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScenarioUpdate) SetUpdatedAt(v time.Time) *ScenarioUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ScenarioUpdate) SetCreatorID(id int) *ScenarioUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ScenarioUpdate) SetCreator(v *User) *ScenarioUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddObjectiveIDs adds the "objectives" edge to the Objective entity by IDs.
func (_u *ScenarioUpdate) AddObjectiveIDs(ids ...int) *ScenarioUpdate {
	_u.mutation.AddObjectiveIDs(ids...)
	return _u
}

// AddObjectives adds the "objectives" edges to the Objective entity.
func (_u *ScenarioUpdate) AddObjectives(v ...*Objective) *ScenarioUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddObjectiveIDs(ids...)
}

// Mutation returns the ScenarioMutation object of the builder.
func (_u *ScenarioUpdate) Mutation() *ScenarioMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ScenarioUpdate) ClearCreator() *ScenarioUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearObjectives clears all "objectives" edges to the Objective entity.
func (_u *ScenarioUpdate) ClearObjectives() *ScenarioUpdate {
	_u.mutation.ClearObjectives()
	return _u
}

// RemoveObjectiveIDs removes the "objectives" edge to Objective entities by IDs.
func (_u *ScenarioUpdate) RemoveObjectiveIDs(ids ...int) *ScenarioUpdate {
	_u.mutation.RemoveObjectiveIDs(ids...)
	return _u
}

// RemoveObjectives removes "objectives" edges to Objective entities.
func (_u *ScenarioUpdate) RemoveObjectives(v ...*Objective) *ScenarioUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveObjectiveIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScenarioUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScenarioUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScenarioUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScenarioUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScenarioUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scenario.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScenarioUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := scenario.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Scenario.name": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Scenario.creator"`)
	}
	return nil
}

func (_u *ScenarioUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scenario.Table, scenario.Columns, sqlgraph.NewFieldSpec(scenario.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scenario.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(scenario.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(scenario.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Topology(); ok {
		_spec.SetField(scenario.FieldTopology, field.TypeString, value)
	}
	if _u.mutation.TopologyCleared() {
		_spec.ClearField(scenario.FieldTopology, field.TypeString)
	}
	if value, ok := _u.mutation.DockerCompose(); ok {
		_spec.SetField(scenario.FieldDockerCompose, field.TypeString, value)
	}
	if _u.mutation.DockerComposeCleared() {
		_spec.ClearField(scenario.FieldDockerCompose, field.TypeString)
	}
	if value, ok := _u.mutation.NetworkConfig(); ok {
		_spec.SetField(scenario.FieldNetworkConfig, field.TypeJSON, value)
	}
	if _u.mutation.NetworkConfigCleared() {
		_spec.ClearField(scenario.FieldNetworkConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Difficulty(); ok {
		_spec.SetField(scenario.FieldDifficulty, field.TypeString, value)
	}
	if _u.mutation.DifficultyCleared() {
		_spec.ClearField(scenario.FieldDifficulty, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedDuration(); ok {
		_spec.SetField(scenario.FieldEstimatedDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedDuration(); ok {
		_spec.AddField(scenario.FieldEstimatedDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(scenario.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, scenario.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(scenario.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scenario.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scenario.CreatorTable,
			Columns: []string{scenario.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scenario.CreatorTable,
			Columns: []string{scenario.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ObjectivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scenario.ObjectivesTable,
			Columns: []string{scenario.ObjectivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objective.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedObjectivesIDs(); len(nodes) > 0 && !_u.mutation.ObjectivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scenario.ObjectivesTable,
			Columns: []string{scenario.ObjectivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objective.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ObjectivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scenario.ObjectivesTable,
			Columns: []string{scenario.ObjectivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objective.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scenario.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScenarioUpdateOne is the builder for updating a single Scenario entity.
type ScenarioUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScenarioMutation
}

// SetName sets the "name" field.
func (_u *ScenarioUpdateOne) SetName(v string) *ScenarioUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableName(v *string) *ScenarioUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScenarioUpdateOne) SetDescription(v string) *ScenarioUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableDescription(v *string) *ScenarioUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScenarioUpdateOne) ClearDescription() *ScenarioUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTopology sets the "topology" field.
func (_u *ScenarioUpdateOne) SetTopology(v string) *ScenarioUpdateOne {
	_u.mutation.SetTopology(v)
	return _u
}

// SetNillableTopology sets the "topology" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableTopology(v *string) *ScenarioUpdateOne {
	if v != nil {
		_u.SetTopology(*v)
	}
	return _u
}

// ClearTopology clears the value of the "topology" field.
func (_u *ScenarioUpdateOne) ClearTopology() *ScenarioUpdateOne {
	_u.mutation.ClearTopology()
	return _u
}

// SetDockerCompose sets the "docker_compose" field.
func (_u *ScenarioUpdateOne) SetDockerCompose(v string) *ScenarioUpdateOne {
	_u.mutation.SetDockerCompose(v)
	return _u
}

// SetNillableDockerCompose sets the "docker_compose" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableDockerCompose(v *string) *ScenarioUpdateOne {
	if v != nil {
		_u.SetDockerCompose(*v)
	}
	return _u
}

// ClearDockerCompose clears the value of the "docker_compose" field.
func (_u *ScenarioUpdateOne) ClearDockerCompose() *ScenarioUpdateOne {
	_u.mutation.ClearDockerCompose()
	return _u
}

// SetNetworkConfig sets the "network_config" field.
func (_u *ScenarioUpdateOne) SetNetworkConfig(v map[string]interface{}) *ScenarioUpdateOne {
	_u.mutation.SetNetworkConfig(v)
	return _u
}

// ClearNetworkConfig clears the value of the "network_config" field.
func (_u *ScenarioUpdateOne) ClearNetworkConfig() *ScenarioUpdateOne {
	_u.mutation.ClearNetworkConfig()
	return _u
}

// SetDifficulty sets the "difficulty" field.
func (_u *ScenarioUpdateOne) SetDifficulty(v string) *ScenarioUpdateOne {
	_u.mutation.SetDifficulty(v)
	return _u
}

// SetNillableDifficulty sets the "difficulty" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableDifficulty(v *string) *ScenarioUpdateOne {
	if v != nil {
		_u.SetDifficulty(*v)
	}
	return _u
}

// ClearDifficulty clears the value of the "difficulty" field.
func (_u *ScenarioUpdateOne) ClearDifficulty() *ScenarioUpdateOne {
	_u.mutation.ClearDifficulty()
	return _u
}

// SetEstimatedDuration sets the "estimated_duration" field.
func (_u *ScenarioUpdateOne) SetEstimatedDuration(v int) *ScenarioUpdateOne {
	_u.mutation.ResetEstimatedDuration()
	_u.mutation.SetEstimatedDuration(v)
	return _u
}

// SetNillableEstimatedDuration sets the "estimated_duration" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableEstimatedDuration(v *int) *ScenarioUpdateOne {
	if v != nil {
		_u.SetEstimatedDuration(*v)
	}
	return _u
}

// AddEstimatedDuration adds value to the "estimated_duration" field.
func (_u *ScenarioUpdateOne) AddEstimatedDuration(v int) *ScenarioUpdateOne {
	_u.mutation.AddEstimatedDuration(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *ScenarioUpdateOne) SetTags(v []string) *ScenarioUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ScenarioUpdateOne) AppendTags(v []string) *ScenarioUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *ScenarioUpdateOne) ClearTags() *ScenarioUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ScenarioUpdateOne) SetCreatedBy(v int) *ScenarioUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ScenarioUpdateOne) SetNillableCreatedBy(v *int) *ScenarioUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScenarioUpdateOne) SetUpdatedAt(v time.Time) *ScenarioUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ScenarioUpdateOne) SetCreatorID(id int) *ScenarioUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ScenarioUpdateOne) SetCreator(v *User) *ScenarioUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddObjectiveIDs adds the "objectives" edge to the Objective entity by IDs.
func (_u *ScenarioUpdateOne) AddObjectiveIDs(ids ...int) *ScenarioUpdateOne {
	_u.mutation.AddObjectiveIDs(ids...)
	return _u
}

// AddObjectives adds the "objectives" edges to the Objective entity.
func (_u *ScenarioUpdateOne) AddObjectives(v ...*Objective) *ScenarioUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddObjectiveIDs(ids...)
}

// Mutation returns the ScenarioMutation object of the builder.
func (_u *ScenarioUpdateOne) Mutation() *ScenarioMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ScenarioUpdateOne) ClearCreator() *ScenarioUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearObjectives clears all "objectives" edges to the Objective entity.
func (_u *ScenarioUpdateOne) ClearObjectives() *ScenarioUpdateOne {
	_u.mutation.ClearObjectives()
	return _u
}

// RemoveObjectiveIDs removes the "objectives" edge to Objective entities by IDs.
func (_u *ScenarioUpdateOne) RemoveObjectiveIDs(ids ...int) *ScenarioUpdateOne {
	_u.mutation.RemoveObjectiveIDs(ids...)
	return _u
}

// RemoveObjectives removes "objectives" edges to Objective entities.
func (_u *ScenarioUpdateOne) RemoveObjectives(v ...*Objective) *ScenarioUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveObjectiveIDs(ids...)
}

// Where appends a list predicates to the ScenarioUpdate builder.
func (_u *ScenarioUpdateOne) Where(ps ...predicate.Scenario) *ScenarioUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScenarioUpdateOne) Select(field string, fields ...string) *ScenarioUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Scenario entity.
func (_u *ScenarioUpdateOne) Save(ctx context.Context) (*Scenario, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScenarioUpdateOne) SaveX(ctx context.Context) *Scenario {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScenarioUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScenarioUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScenarioUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scenario.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScenarioUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := scenario.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Scenario.name": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Scenario.creator"`)
	}
	return nil
}

func (_u *ScenarioUpdateOne) sqlSave(ctx context.Context) (_node *Scenario, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scenario.Table, scenario.Columns, sqlgraph.NewFieldSpec(scenario.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Scenario.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scenario.FieldID)
		for _, f := range fields {
			if !scenario.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scenario.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scenario.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(scenario.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(scenario.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Topology(); ok {
		_spec.SetField(scenario.FieldTopology, field.TypeString, value)
	}
	if _u.mutation.TopologyCleared() {
		_spec.ClearField(scenario.FieldTopology, field.TypeString)
	}
	if value, ok := _u.mutation.DockerCompose(); ok {
		_spec.SetField(scenario.FieldDockerCompose, field.TypeString, value)
	}
	if _u.mutation.DockerComposeCleared() {
		_spec.ClearField(scenario.FieldDockerCompose, field.TypeString)
	}
	if value, ok := _u.mutation.NetworkConfig(); ok {
		_spec.SetField(scenario.FieldNetworkConfig, field.TypeJSON, value)
	}
	if _u.mutation.NetworkConfigCleared() {
		_spec.ClearField(scenario.FieldNetworkConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Difficulty(); ok {
		_spec.SetField(scenario.FieldDifficulty, field.TypeString, value)
	}
	if _u.mutation.DifficultyCleared() {
		_spec.ClearField(scenario.FieldDifficulty, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedDuration(); ok {
		_spec.SetField(scenario.FieldEstimatedDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedDuration(); ok {
		_spec.AddField(scenario.FieldEstimatedDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(scenario.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, scenario.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(scenario.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scenario.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scenario.CreatorTable,
			Columns: []string{scenario.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scenario.CreatorTable,
			Columns: []string{scenario.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ObjectivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scenario.ObjectivesTable,
			Columns: []string{scenario.ObjectivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objective.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedObjectivesIDs(); len(nodes) > 0 && !_u.mutation.ObjectivesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scenario.ObjectivesTable,
			Columns: []string{scenario.ObjectivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objective.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ObjectivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scenario.ObjectivesTable,
			Columns: []string{scenario.ObjectivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objective.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Scenario{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scenario.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
