// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ZacharyZcR/STC/backend/ent/role"
	"github.com/ZacharyZcR/STC/backend/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"-"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Nickname holds the value of the "nickname" field.
	Nickname string `json:"nickname,omitempty"`
	// Avatar holds the value of the "avatar" field.
	Avatar string `json:"avatar,omitempty"`
	// OauthProvider holds the value of the "oauth_provider" field.
	OauthProvider string `json:"oauth_provider,omitempty"`
	// OauthID holds the value of the "oauth_id" field.
	OauthID string `json:"oauth_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	role_users   *int
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// Projects holds the value of the projects edge.
	Projects []*Project `json:"projects,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// Conversations holds the value of the conversations edge.
	Conversations []*Conversation `json:"conversations,omitempty"`
	// Competitions holds the value of the competitions edge.
	Competitions []*Competition `json:"competitions,omitempty"`
	// AuthoredChallenges holds the value of the authored_challenges edge.
	AuthoredChallenges []*Challenge `json:"authored_challenges,omitempty"`
	// CaptainedTeams holds the value of the captained_teams edge.
	CaptainedTeams []*Team `json:"captained_teams,omitempty"`
	// TeamMemberships holds the value of the team_memberships edge.
	TeamMemberships []*TeamMember `json:"team_memberships,omitempty"`
	// FlagSubmissions holds the value of the flag_submissions edge.
	FlagSubmissions []*FlagSubmission `json:"flag_submissions,omitempty"`
	// Writeups holds the value of the writeups edge.
	Writeups []*Writeup `json:"writeups,omitempty"`
	// Scenarios holds the value of the scenarios edge.
	Scenarios []*Scenario `json:"scenarios,omitempty"`
	// AttackReports holds the value of the attack_reports edge.
	AttackReports []*AttackReport `json:"attack_reports,omitempty"`
	// DefenseReports holds the value of the defense_reports edge.
	DefenseReports []*DefenseReport `json:"defense_reports,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [13]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// ProjectsOrErr returns the Projects value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[1] {
		return e.Projects, nil
	}
	return nil, &NotLoadedError{edge: "projects"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[2] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// ConversationsOrErr returns the Conversations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ConversationsOrErr() ([]*Conversation, error) {
	if e.loadedTypes[3] {
		return e.Conversations, nil
	}
	return nil, &NotLoadedError{edge: "conversations"}
}

// CompetitionsOrErr returns the Competitions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CompetitionsOrErr() ([]*Competition, error) {
	if e.loadedTypes[4] {
		return e.Competitions, nil
	}
	return nil, &NotLoadedError{edge: "competitions"}
}

// AuthoredChallengesOrErr returns the AuthoredChallenges value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AuthoredChallengesOrErr() ([]*Challenge, error) {
	if e.loadedTypes[5] {
		return e.AuthoredChallenges, nil
	}
	return nil, &NotLoadedError{edge: "authored_challenges"}
}

// CaptainedTeamsOrErr returns the CaptainedTeams value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CaptainedTeamsOrErr() ([]*Team, error) {
	if e.loadedTypes[6] {
		return e.CaptainedTeams, nil
	}
	return nil, &NotLoadedError{edge: "captained_teams"}
}

// TeamMembershipsOrErr returns the TeamMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TeamMembershipsOrErr() ([]*TeamMember, error) {
	if e.loadedTypes[7] {
		return e.TeamMemberships, nil
	}
	return nil, &NotLoadedError{edge: "team_memberships"}
}

// FlagSubmissionsOrErr returns the FlagSubmissions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FlagSubmissionsOrErr() ([]*FlagSubmission, error) {
	if e.loadedTypes[8] {
		return e.FlagSubmissions, nil
	}
	return nil, &NotLoadedError{edge: "flag_submissions"}
}

// WriteupsOrErr returns the Writeups value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) WriteupsOrErr() ([]*Writeup, error) {
	if e.loadedTypes[9] {
		return e.Writeups, nil
	}
	return nil, &NotLoadedError{edge: "writeups"}
}

// ScenariosOrErr returns the Scenarios value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ScenariosOrErr() ([]*Scenario, error) {
	if e.loadedTypes[10] {
		return e.Scenarios, nil
	}
	return nil, &NotLoadedError{edge: "scenarios"}
}

// AttackReportsOrErr returns the AttackReports value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AttackReportsOrErr() ([]*AttackReport, error) {
	if e.loadedTypes[11] {
		return e.AttackReports, nil
	}
	return nil, &NotLoadedError{edge: "attack_reports"}
}

// DefenseReportsOrErr returns the DefenseReports value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) DefenseReportsOrErr() ([]*DefenseReport, error) {
	if e.loadedTypes[12] {
		return e.DefenseReports, nil
	}
	return nil, &NotLoadedError{edge: "defense_reports"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldPassword, user.FieldEmail, user.FieldNickname, user.FieldAvatar, user.FieldOauthProvider, user.FieldOauthID:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.ForeignKeys[0]: // role_users
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				_m.Nickname = value.String
			}
		case user.FieldAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar", values[i])
			} else if value.Valid {
				_m.Avatar = value.String
			}
		case user.FieldOauthProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oauth_provider", values[i])
			} else if value.Valid {
				_m.OauthProvider = value.String
			}
		case user.FieldOauthID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oauth_id", values[i])
			} else if value.Valid {
				_m.OauthID = value.String
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field role_users", value)
			} else if value.Valid {
				_m.role_users = new(int)
				*_m.role_users = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the User entity.
func (_m *User) QueryRole() *RoleQuery {
	return NewUserClient(_m.config).QueryRole(_m)
}

// QueryProjects queries the "projects" edge of the User entity.
func (_m *User) QueryProjects() *ProjectQuery {
	return NewUserClient(_m.config).QueryProjects(_m)
}

// QueryNotifications queries the "notifications" edge of the User entity.
func (_m *User) QueryNotifications() *NotificationQuery {
	return NewUserClient(_m.config).QueryNotifications(_m)
}

// QueryConversations queries the "conversations" edge of the User entity.
func (_m *User) QueryConversations() *ConversationQuery {
	return NewUserClient(_m.config).QueryConversations(_m)
}

// QueryCompetitions queries the "competitions" edge of the User entity.
func (_m *User) QueryCompetitions() *CompetitionQuery {
	return NewUserClient(_m.config).QueryCompetitions(_m)
}

// QueryAuthoredChallenges queries the "authored_challenges" edge of the User entity.
func (_m *User) QueryAuthoredChallenges() *ChallengeQuery {
	return NewUserClient(_m.config).QueryAuthoredChallenges(_m)
}

// QueryCaptainedTeams queries the "captained_teams" edge of the User entity.
func (_m *User) QueryCaptainedTeams() *TeamQuery {
	return NewUserClient(_m.config).QueryCaptainedTeams(_m)
}

// QueryTeamMemberships queries the "team_memberships" edge of the User entity.
func (_m *User) QueryTeamMemberships() *TeamMemberQuery {
	return NewUserClient(_m.config).QueryTeamMemberships(_m)
}

// QueryFlagSubmissions queries the "flag_submissions" edge of the User entity.
func (_m *User) QueryFlagSubmissions() *FlagSubmissionQuery {
	return NewUserClient(_m.config).QueryFlagSubmissions(_m)
}

// QueryWriteups queries the "writeups" edge of the User entity.
func (_m *User) QueryWriteups() *WriteupQuery {
	return NewUserClient(_m.config).QueryWriteups(_m)
}

// QueryScenarios queries the "scenarios" edge of the User entity.
func (_m *User) QueryScenarios() *ScenarioQuery {
	return NewUserClient(_m.config).QueryScenarios(_m)
}

// QueryAttackReports queries the "attack_reports" edge of the User entity.
func (_m *User) QueryAttackReports() *AttackReportQuery {
	return NewUserClient(_m.config).QueryAttackReports(_m)
}

// QueryDefenseReports queries the "defense_reports" edge of the User entity.
func (_m *User) QueryDefenseReports() *DefenseReportQuery {
	return NewUserClient(_m.config).QueryDefenseReports(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("nickname=")
	builder.WriteString(_m.Nickname)
	builder.WriteString(", ")
	builder.WriteString("avatar=")
	builder.WriteString(_m.Avatar)
	builder.WriteString(", ")
	builder.WriteString("oauth_provider=")
	builder.WriteString(_m.OauthProvider)
	builder.WriteString(", ")
	builder.WriteString("oauth_id=")
	builder.WriteString(_m.OauthID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
