// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/attackreport"
	"github.com/ZacharyZcR/STC/backend/ent/challenge"
	"github.com/ZacharyZcR/STC/backend/ent/competition"
	"github.com/ZacharyZcR/STC/backend/ent/conversation"
	"github.com/ZacharyZcR/STC/backend/ent/defensereport"
	"github.com/ZacharyZcR/STC/backend/ent/flagsubmission"
	"github.com/ZacharyZcR/STC/backend/ent/notification"
	"github.com/ZacharyZcR/STC/backend/ent/predicate"
	"github.com/ZacharyZcR/STC/backend/ent/project"
	"github.com/ZacharyZcR/STC/backend/ent/role"
	"github.com/ZacharyZcR/STC/backend/ent/scenario"
	"github.com/ZacharyZcR/STC/backend/ent/team"
	"github.com/ZacharyZcR/STC/backend/ent/teammember"
	"github.com/ZacharyZcR/STC/backend/ent/user"
	"github.com/ZacharyZcR/STC/backend/ent/writeup"
)

// UserQuery is the builder for querying User entities.
type UserQuery struct {
	config
	ctx                    *QueryContext
	order                  []user.OrderOption
	inters                 []Interceptor
	predicates             []predicate.User
	withRole               *RoleQuery
	withProjects           *ProjectQuery
	withNotifications      *NotificationQuery
	withConversations      *ConversationQuery
	withCompetitions       *CompetitionQuery
	withAuthoredChallenges *ChallengeQuery
	withCaptainedTeams     *TeamQuery
	withTeamMemberships    *TeamMemberQuery
	withFlagSubmissions    *FlagSubmissionQuery
	withWriteups           *WriteupQuery
	withScenarios          *ScenarioQuery
	withAttackReports      *AttackReportQuery
	withDefenseReports     *DefenseReportQuery
	withFKs                bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserQuery builder.
func (_q *UserQuery) Where(ps ...predicate.User) *UserQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UserQuery) Limit(limit int) *UserQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UserQuery) Offset(offset int) *UserQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UserQuery) Unique(unique bool) *UserQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UserQuery) Order(o ...user.OrderOption) *UserQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRole chains the current query on the "role" edge.
func (_q *UserQuery) QueryRole() *RoleQuery {
	query := (&RoleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.RoleTable, user.RoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProjects chains the current query on the "projects" edge.
func (_q *UserQuery) QueryProjects() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.ProjectsTable, user.ProjectsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNotifications chains the current query on the "notifications" edge.
func (_q *UserQuery) QueryNotifications() *NotificationQuery {
	query := (&NotificationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(notification.Table, notification.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.NotificationsTable, user.NotificationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryConversations chains the current query on the "conversations" edge.
func (_q *UserQuery) QueryConversations() *ConversationQuery {
	query := (&ConversationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(conversation.Table, conversation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.ConversationsTable, user.ConversationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCompetitions chains the current query on the "competitions" edge.
func (_q *UserQuery) QueryCompetitions() *CompetitionQuery {
	query := (&CompetitionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(competition.Table, competition.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CompetitionsTable, user.CompetitionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAuthoredChallenges chains the current query on the "authored_challenges" edge.
func (_q *UserQuery) QueryAuthoredChallenges() *ChallengeQuery {
	query := (&ChallengeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(challenge.Table, challenge.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.AuthoredChallengesTable, user.AuthoredChallengesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCaptainedTeams chains the current query on the "captained_teams" edge.
func (_q *UserQuery) QueryCaptainedTeams() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.CaptainedTeamsTable, user.CaptainedTeamsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeamMemberships chains the current query on the "team_memberships" edge.
func (_q *UserQuery) QueryTeamMemberships() *TeamMemberQuery {
	query := (&TeamMemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(teammember.Table, teammember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.TeamMembershipsTable, user.TeamMembershipsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFlagSubmissions chains the current query on the "flag_submissions" edge.
func (_q *UserQuery) QueryFlagSubmissions() *FlagSubmissionQuery {
	query := (&FlagSubmissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(flagsubmission.Table, flagsubmission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.FlagSubmissionsTable, user.FlagSubmissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWriteups chains the current query on the "writeups" edge.
func (_q *UserQuery) QueryWriteups() *WriteupQuery {
	query := (&WriteupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(writeup.Table, writeup.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.WriteupsTable, user.WriteupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScenarios chains the current query on the "scenarios" edge.
func (_q *UserQuery) QueryScenarios() *ScenarioQuery {
	query := (&ScenarioClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(scenario.Table, scenario.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.ScenariosTable, user.ScenariosColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttackReports chains the current query on the "attack_reports" edge.
func (_q *UserQuery) QueryAttackReports() *AttackReportQuery {
	query := (&AttackReportClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(attackreport.Table, attackreport.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.AttackReportsTable, user.AttackReportsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDefenseReports chains the current query on the "defense_reports" edge.
func (_q *UserQuery) QueryDefenseReports() *DefenseReportQuery {
	query := (&DefenseReportClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, selector),
			sqlgraph.To(defensereport.Table, defensereport.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.DefenseReportsTable, user.DefenseReportsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first User entity from the query.
// Returns a *NotFoundError when no User was found.
func (_q *UserQuery) First(ctx context.Context) (*User, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{user.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UserQuery) FirstX(ctx context.Context) *User {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first User ID from the query.
// Returns a *NotFoundError when no User ID was found.
func (_q *UserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{user.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UserQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single User entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one User entity is found.
// Returns a *NotFoundError when no User entities are found.
func (_q *UserQuery) Only(ctx context.Context) (*User, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{user.Label}
	default:
		return nil, &NotSingularError{user.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UserQuery) OnlyX(ctx context.Context) *User {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only User ID in the query.
// Returns a *NotSingularError when more than one User ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{user.Label}
	default:
		err = &NotSingularError{user.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UserQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Users.
func (_q *UserQuery) All(ctx context.Context) ([]*User, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*User, *UserQuery]()
	return withInterceptors[[]*User](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UserQuery) AllX(ctx context.Context) []*User {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of User IDs.
func (_q *UserQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(user.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UserQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UserQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UserQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UserQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UserQuery) Clone() *UserQuery {
	if _q == nil {
		return nil
	}
	return &UserQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]user.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.User{}, _q.predicates...),
		withRole:               _q.withRole.Clone(),
		withProjects:           _q.withProjects.Clone(),
		withNotifications:      _q.withNotifications.Clone(),
		withConversations:      _q.withConversations.Clone(),
		withCompetitions:       _q.withCompetitions.Clone(),
		withAuthoredChallenges: _q.withAuthoredChallenges.Clone(),
		withCaptainedTeams:     _q.withCaptainedTeams.Clone(),
		withTeamMemberships:    _q.withTeamMemberships.Clone(),
		withFlagSubmissions:    _q.withFlagSubmissions.Clone(),
		withWriteups:           _q.withWriteups.Clone(),
		withScenarios:          _q.withScenarios.Clone(),
		withAttackReports:      _q.withAttackReports.Clone(),
		withDefenseReports:     _q.withDefenseReports.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRole tells the query-builder to eager-load the nodes that are connected to
// the "role" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithRole(opts ...func(*RoleQuery)) *UserQuery {
	query := (&RoleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRole = query
	return _q
}

// WithProjects tells the query-builder to eager-load the nodes that are connected to
// the "projects" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithProjects(opts ...func(*ProjectQuery)) *UserQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProjects = query
	return _q
}

// WithNotifications tells the query-builder to eager-load the nodes that are connected to
// the "notifications" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithNotifications(opts ...func(*NotificationQuery)) *UserQuery {
	query := (&NotificationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNotifications = query
	return _q
}

// WithConversations tells the query-builder to eager-load the nodes that are connected to
// the "conversations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithConversations(opts ...func(*ConversationQuery)) *UserQuery {
	query := (&ConversationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConversations = query
	return _q
}

// WithCompetitions tells the query-builder to eager-load the nodes that are connected to
// the "competitions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithCompetitions(opts ...func(*CompetitionQuery)) *UserQuery {
	query := (&CompetitionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCompetitions = query
	return _q
}

// WithAuthoredChallenges tells the query-builder to eager-load the nodes that are connected to
// the "authored_challenges" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithAuthoredChallenges(opts ...func(*ChallengeQuery)) *UserQuery {
	query := (&ChallengeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAuthoredChallenges = query
	return _q
}

// WithCaptainedTeams tells the query-builder to eager-load the nodes that are connected to
// the "captained_teams" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithCaptainedTeams(opts ...func(*TeamQuery)) *UserQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCaptainedTeams = query
	return _q
}

// WithTeamMemberships tells the query-builder to eager-load the nodes that are connected to
// the "team_memberships" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithTeamMemberships(opts ...func(*TeamMemberQuery)) *UserQuery {
	query := (&TeamMemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeamMemberships = query
	return _q
}

// WithFlagSubmissions tells the query-builder to eager-load the nodes that are connected to
// the "flag_submissions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithFlagSubmissions(opts ...func(*FlagSubmissionQuery)) *UserQuery {
	query := (&FlagSubmissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFlagSubmissions = query
	return _q
}

// WithWriteups tells the query-builder to eager-load the nodes that are connected to
// the "writeups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithWriteups(opts ...func(*WriteupQuery)) *UserQuery {
	query := (&WriteupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWriteups = query
	return _q
}

// WithScenarios tells the query-builder to eager-load the nodes that are connected to
// the "scenarios" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithScenarios(opts ...func(*ScenarioQuery)) *UserQuery {
	query := (&ScenarioClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withScenarios = query
	return _q
}

// WithAttackReports tells the query-builder to eager-load the nodes that are connected to
// the "attack_reports" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithAttackReports(opts ...func(*AttackReportQuery)) *UserQuery {
	query := (&AttackReportClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttackReports = query
	return _q
}

// WithDefenseReports tells the query-builder to eager-load the nodes that are connected to
// the "defense_reports" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserQuery) WithDefenseReports(opts ...func(*DefenseReportQuery)) *UserQuery {
	query := (&DefenseReportClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDefenseReports = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.User.Query().
//		GroupBy(user.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UserQuery) GroupBy(field string, fields ...string) *UserGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = user.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.User.Query().
//		Select(user.FieldUsername).
//		Scan(ctx, &v)
func (_q *UserQuery) Select(fields ...string) *UserSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UserSelect{UserQuery: _q}
	sbuild.label = user.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserSelect configured with the given aggregations.
func (_q *UserQuery) Aggregate(fns ...AggregateFunc) *UserSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !user.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*User, error) {
	var (
		nodes       = []*User{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [13]bool{
			_q.withRole != nil,
			_q.withProjects != nil,
			_q.withNotifications != nil,
			_q.withConversations != nil,
			_q.withCompetitions != nil,
			_q.withAuthoredChallenges != nil,
			_q.withCaptainedTeams != nil,
			_q.withTeamMemberships != nil,
			_q.withFlagSubmissions != nil,
			_q.withWriteups != nil,
			_q.withScenarios != nil,
			_q.withAttackReports != nil,
			_q.withDefenseReports != nil,
		}
	)
	if _q.withRole != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, user.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*User).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &User{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRole; query != nil {
		if err := _q.loadRole(ctx, query, nodes, nil,
			func(n *User, e *Role) { n.Edges.Role = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProjects; query != nil {
		if err := _q.loadProjects(ctx, query, nodes,
			func(n *User) { n.Edges.Projects = []*Project{} },
			func(n *User, e *Project) { n.Edges.Projects = append(n.Edges.Projects, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNotifications; query != nil {
		if err := _q.loadNotifications(ctx, query, nodes,
			func(n *User) { n.Edges.Notifications = []*Notification{} },
			func(n *User, e *Notification) { n.Edges.Notifications = append(n.Edges.Notifications, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withConversations; query != nil {
		if err := _q.loadConversations(ctx, query, nodes,
			func(n *User) { n.Edges.Conversations = []*Conversation{} },
			func(n *User, e *Conversation) { n.Edges.Conversations = append(n.Edges.Conversations, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCompetitions; query != nil {
		if err := _q.loadCompetitions(ctx, query, nodes,
			func(n *User) { n.Edges.Competitions = []*Competition{} },
			func(n *User, e *Competition) { n.Edges.Competitions = append(n.Edges.Competitions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAuthoredChallenges; query != nil {
		if err := _q.loadAuthoredChallenges(ctx, query, nodes,
			func(n *User) { n.Edges.AuthoredChallenges = []*Challenge{} },
			func(n *User, e *Challenge) { n.Edges.AuthoredChallenges = append(n.Edges.AuthoredChallenges, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCaptainedTeams; query != nil {
		if err := _q.loadCaptainedTeams(ctx, query, nodes,
			func(n *User) { n.Edges.CaptainedTeams = []*Team{} },
			func(n *User, e *Team) { n.Edges.CaptainedTeams = append(n.Edges.CaptainedTeams, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTeamMemberships; query != nil {
		if err := _q.loadTeamMemberships(ctx, query, nodes,
			func(n *User) { n.Edges.TeamMemberships = []*TeamMember{} },
			func(n *User, e *TeamMember) { n.Edges.TeamMemberships = append(n.Edges.TeamMemberships, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFlagSubmissions; query != nil {
		if err := _q.loadFlagSubmissions(ctx, query, nodes,
			func(n *User) { n.Edges.FlagSubmissions = []*FlagSubmission{} },
			func(n *User, e *FlagSubmission) { n.Edges.FlagSubmissions = append(n.Edges.FlagSubmissions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWriteups; query != nil {
		if err := _q.loadWriteups(ctx, query, nodes,
			func(n *User) { n.Edges.Writeups = []*Writeup{} },
			func(n *User, e *Writeup) { n.Edges.Writeups = append(n.Edges.Writeups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withScenarios; query != nil {
		if err := _q.loadScenarios(ctx, query, nodes,
			func(n *User) { n.Edges.Scenarios = []*Scenario{} },
			func(n *User, e *Scenario) { n.Edges.Scenarios = append(n.Edges.Scenarios, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAttackReports; query != nil {
		if err := _q.loadAttackReports(ctx, query, nodes,
			func(n *User) { n.Edges.AttackReports = []*AttackReport{} },
			func(n *User, e *AttackReport) { n.Edges.AttackReports = append(n.Edges.AttackReports, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDefenseReports; query != nil {
		if err := _q.loadDefenseReports(ctx, query, nodes,
			func(n *User) { n.Edges.DefenseReports = []*DefenseReport{} },
			func(n *User, e *DefenseReport) { n.Edges.DefenseReports = append(n.Edges.DefenseReports, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UserQuery) loadRole(ctx context.Context, query *RoleQuery, nodes []*User, init func(*User), assign func(*User, *Role)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*User)
	for i := range nodes {
		if nodes[i].role_users == nil {
			continue
		}
		fk := *nodes[i].role_users
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "role_users" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UserQuery) loadProjects(ctx context.Context, query *ProjectQuery, nodes []*User, init func(*User), assign func(*User, *Project)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(project.FieldOwnerID)
	}
	query.Where(predicate.Project(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.ProjectsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OwnerID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "owner_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadNotifications(ctx context.Context, query *NotificationQuery, nodes []*User, init func(*User), assign func(*User, *Notification)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(notification.FieldUserID)
	}
	query.Where(predicate.Notification(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.NotificationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadConversations(ctx context.Context, query *ConversationQuery, nodes []*User, init func(*User), assign func(*User, *Conversation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(conversation.FieldUserID)
	}
	query.Where(predicate.Conversation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.ConversationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadCompetitions(ctx context.Context, query *CompetitionQuery, nodes []*User, init func(*User), assign func(*User, *Competition)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(competition.FieldCreatedBy)
	}
	query.Where(predicate.Competition(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.CompetitionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CreatedBy
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "created_by" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadAuthoredChallenges(ctx context.Context, query *ChallengeQuery, nodes []*User, init func(*User), assign func(*User, *Challenge)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(challenge.FieldAuthorID)
	}
	query.Where(predicate.Challenge(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.AuthoredChallengesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AuthorID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "author_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadCaptainedTeams(ctx context.Context, query *TeamQuery, nodes []*User, init func(*User), assign func(*User, *Team)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(team.FieldCaptainID)
	}
	query.Where(predicate.Team(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.CaptainedTeamsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CaptainID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "captain_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadTeamMemberships(ctx context.Context, query *TeamMemberQuery, nodes []*User, init func(*User), assign func(*User, *TeamMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(teammember.FieldUserID)
	}
	query.Where(predicate.TeamMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.TeamMembershipsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadFlagSubmissions(ctx context.Context, query *FlagSubmissionQuery, nodes []*User, init func(*User), assign func(*User, *FlagSubmission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(flagsubmission.FieldUserID)
	}
	query.Where(predicate.FlagSubmission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.FlagSubmissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadWriteups(ctx context.Context, query *WriteupQuery, nodes []*User, init func(*User), assign func(*User, *Writeup)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(writeup.FieldUserID)
	}
	query.Where(predicate.Writeup(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.WriteupsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadScenarios(ctx context.Context, query *ScenarioQuery, nodes []*User, init func(*User), assign func(*User, *Scenario)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(scenario.FieldCreatedBy)
	}
	query.Where(predicate.Scenario(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.ScenariosColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CreatedBy
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "created_by" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadAttackReports(ctx context.Context, query *AttackReportQuery, nodes []*User, init func(*User), assign func(*User, *AttackReport)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(attackreport.FieldUserID)
	}
	query.Where(predicate.AttackReport(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.AttackReportsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UserQuery) loadDefenseReports(ctx context.Context, query *DefenseReportQuery, nodes []*User, init func(*User), assign func(*User, *DefenseReport)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*User)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(defensereport.FieldUserID)
	}
	query.Where(predicate.DefenseReport(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(user.DefenseReportsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UserID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *UserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for i := range fields {
			if fields[i] != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(user.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = user.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserGroupBy is the group-by builder for User entities.
type UserGroupBy struct {
	selector
	build *UserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UserGroupBy) Aggregate(fns ...AggregateFunc) *UserGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserQuery, *UserGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UserGroupBy) sqlScan(ctx context.Context, root *UserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserSelect is the builder for selecting fields of User entities.
type UserSelect struct {
	*UserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UserSelect) Aggregate(fns ...AggregateFunc) *UserSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserQuery, *UserSelect](ctx, _s.UserQuery, _s, _s.inters, v)
}

func (_s *UserSelect) sqlScan(ctx context.Context, root *UserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
