// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ZacharyZcR/STC/backend/ent/webhook"
)

// WebhookCreate is the builder for creating a Webhook entity.
type WebhookCreate struct {
	config
	mutation *WebhookMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *WebhookCreate) SetName(v string) *WebhookCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *WebhookCreate) SetURL(v string) *WebhookCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetSecret sets the "secret" field.
func (_c *WebhookCreate) SetSecret(v string) *WebhookCreate {
	_c.mutation.SetSecret(v)
	return _c
}

// SetNillableSecret sets the "secret" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableSecret(v *string) *WebhookCreate {
	if v != nil {
		_c.SetSecret(*v)
	}
	return _c
}

// SetEvents sets the "events" field.
func (_c *WebhookCreate) SetEvents(v []string) *WebhookCreate {
	_c.mutation.SetEvents(v)
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *WebhookCreate) SetHeaders(v map[string]string) *WebhookCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *WebhookCreate) SetEnabled(v bool) *WebhookCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableEnabled(v *bool) *WebhookCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_c *WebhookCreate) SetLastTriggeredAt(v time.Time) *WebhookCreate {
	_c.mutation.SetLastTriggeredAt(v)
	return _c
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableLastTriggeredAt(v *time.Time) *WebhookCreate {
	if v != nil {
		_c.SetLastTriggeredAt(*v)
	}
	return _c
}

// SetLastStatusCode sets the "last_status_code" field.
func (_c *WebhookCreate) SetLastStatusCode(v int) *WebhookCreate {
	_c.mutation.SetLastStatusCode(v)
	return _c
}

// SetNillableLastStatusCode sets the "last_status_code" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableLastStatusCode(v *int) *WebhookCreate {
	if v != nil {
		_c.SetLastStatusCode(*v)
	}
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *WebhookCreate) SetFailureCount(v int) *WebhookCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableFailureCount(v *int) *WebhookCreate {
	if v != nil {
		_c.SetFailureCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebhookCreate) SetCreatedAt(v time.Time) *WebhookCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableCreatedAt(v *time.Time) *WebhookCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebhookCreate) SetUpdatedAt(v time.Time) *WebhookCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebhookCreate) SetNillableUpdatedAt(v *time.Time) *WebhookCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the WebhookMutation object of the builder.
func (_c *WebhookCreate) Mutation() *WebhookMutation {
	return _c.mutation
}

// Save creates the Webhook in the database.
func (_c *WebhookCreate) Save(ctx context.Context) (*Webhook, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebhookCreate) SaveX(ctx context.Context) *Webhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebhookCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := webhook.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.LastStatusCode(); !ok {
		v := webhook.DefaultLastStatusCode
		_c.mutation.SetLastStatusCode(v)
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		v := webhook.DefaultFailureCount
		_c.mutation.SetFailureCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webhook.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := webhook.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebhookCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Webhook.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := webhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Webhook.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Webhook.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := webhook.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Webhook.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Events(); !ok {
		return &ValidationError{Name: "events", err: errors.New(`ent: missing required field "Webhook.events"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Webhook.enabled"`)}
	}
	if _, ok := _c.mutation.LastStatusCode(); !ok {
		return &ValidationError{Name: "last_status_code", err: errors.New(`ent: missing required field "Webhook.last_status_code"`)}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "Webhook.failure_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Webhook.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Webhook.updated_at"`)}
	}
	return nil
}

func (_c *WebhookCreate) sqlSave(ctx context.Context) (*Webhook, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebhookCreate) createSpec() (*Webhook, *sqlgraph.CreateSpec) {
	var (
		_node = &Webhook{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webhook.Table, sqlgraph.NewFieldSpec(webhook.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(webhook.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(webhook.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Secret(); ok {
		_spec.SetField(webhook.FieldSecret, field.TypeString, value)
		_node.Secret = value
	}
	if value, ok := _c.mutation.Events(); ok {
		_spec.SetField(webhook.FieldEvents, field.TypeJSON, value)
		_node.Events = value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(webhook.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(webhook.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.LastTriggeredAt(); ok {
		_spec.SetField(webhook.FieldLastTriggeredAt, field.TypeTime, value)
		_node.LastTriggeredAt = &value
	}
	if value, ok := _c.mutation.LastStatusCode(); ok {
		_spec.SetField(webhook.FieldLastStatusCode, field.TypeInt, value)
		_node.LastStatusCode = value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(webhook.FieldFailureCount, field.TypeInt, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webhook.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(webhook.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// WebhookCreateBulk is the builder for creating many Webhook entities in bulk.
type WebhookCreateBulk struct {
	config
	err      error
	builders []*WebhookCreate
}

// Save creates the Webhook entities in the database.
func (_c *WebhookCreateBulk) Save(ctx context.Context) ([]*Webhook, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Webhook, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebhookCreateBulk) SaveX(ctx context.Context) []*Webhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
