// Code generated by ent, DO NOT EDIT.

package challengeinstance

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the challengeinstance type in the database.
	Label = "challenge_instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChallengeID holds the string denoting the challenge_id field in the database.
	FieldChallengeID = "challenge_id"
	// FieldCompetitionID holds the string denoting the competition_id field in the database.
	FieldCompetitionID = "competition_id"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// FieldContainerID holds the string denoting the container_id field in the database.
	FieldContainerID = "container_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAccessURL holds the string denoting the access_url field in the database.
	FieldAccessURL = "access_url"
	// FieldPorts holds the string denoting the ports field in the database.
	FieldPorts = "ports"
	// FieldNetworkID holds the string denoting the network_id field in the database.
	FieldNetworkID = "network_id"
	// FieldFlag holds the string denoting the flag field in the database.
	FieldFlag = "flag"
	// FieldSSHUser holds the string denoting the ssh_user field in the database.
	FieldSSHUser = "ssh_user"
	// FieldSSHPassword holds the string denoting the ssh_password field in the database.
	FieldSSHPassword = "ssh_password"
	// FieldSSHAddress holds the string denoting the ssh_address field in the database.
	FieldSSHAddress = "ssh_address"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldStoppedAt holds the string denoting the stopped_at field in the database.
	FieldStoppedAt = "stopped_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeChallenge holds the string denoting the challenge edge name in mutations.
	EdgeChallenge = "challenge"
	// EdgeCompetition holds the string denoting the competition edge name in mutations.
	EdgeCompetition = "competition"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// Table holds the table name of the challengeinstance in the database.
	Table = "challenge_instances"
	// ChallengeTable is the table that holds the challenge relation/edge.
	ChallengeTable = "challenge_instances"
	// ChallengeInverseTable is the table name for the Challenge entity.
	// It exists in this package in order to avoid circular dependency with the "challenge" package.
	ChallengeInverseTable = "challenges"
	// ChallengeColumn is the table column denoting the challenge relation/edge.
	ChallengeColumn = "challenge_id"
	// CompetitionTable is the table that holds the competition relation/edge.
	CompetitionTable = "challenge_instances"
	// CompetitionInverseTable is the table name for the Competition entity.
	// It exists in this package in order to avoid circular dependency with the "competition" package.
	CompetitionInverseTable = "competitions"
	// CompetitionColumn is the table column denoting the competition relation/edge.
	CompetitionColumn = "competition_id"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "challenge_instances"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_id"
)

// Columns holds all SQL columns for challengeinstance fields.
var Columns = []string{
	FieldID,
	FieldChallengeID,
	FieldCompetitionID,
	FieldTeamID,
	FieldContainerID,
	FieldStatus,
	FieldAccessURL,
	FieldPorts,
	FieldNetworkID,
	FieldFlag,
	FieldSSHUser,
	FieldSSHPassword,
	FieldSSHAddress,
	FieldExpiresAt,
	FieldStartedAt,
	FieldStoppedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultContainerID holds the default value on creation for the "container_id" field.
	DefaultContainerID string
	// DefaultAccessURL holds the default value on creation for the "access_url" field.
	DefaultAccessURL string
	// DefaultNetworkID holds the default value on creation for the "network_id" field.
	DefaultNetworkID string
	// DefaultFlag holds the default value on creation for the "flag" field.
	DefaultFlag string
	// DefaultSSHUser holds the default value on creation for the "ssh_user" field.
	DefaultSSHUser string
	// DefaultSSHPassword holds the default value on creation for the "ssh_password" field.
	DefaultSSHPassword string
	// DefaultSSHAddress holds the default value on creation for the "ssh_address" field.
	DefaultSSHAddress string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending  Status = "pending"
	StatusStarting Status = "starting"
	StatusRunning  Status = "running"
	StatusStopping Status = "stopping"
	StatusStopped  Status = "stopped"
	StatusError    Status = "error"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusStarting, StatusRunning, StatusStopping, StatusStopped, StatusError:
		return nil
	default:
		return fmt.Errorf("challengeinstance: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ChallengeInstance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChallengeID orders the results by the challenge_id field.
func ByChallengeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChallengeID, opts...).ToFunc()
}

// ByCompetitionID orders the results by the competition_id field.
func ByCompetitionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompetitionID, opts...).ToFunc()
}

// ByTeamID orders the results by the team_id field.
func ByTeamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamID, opts...).ToFunc()
}

// ByContainerID orders the results by the container_id field.
func ByContainerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContainerID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAccessURL orders the results by the access_url field.
func ByAccessURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessURL, opts...).ToFunc()
}

// ByNetworkID orders the results by the network_id field.
func ByNetworkID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetworkID, opts...).ToFunc()
}

// ByFlag orders the results by the flag field.
func ByFlag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlag, opts...).ToFunc()
}

// BySSHUser orders the results by the ssh_user field.
func BySSHUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHUser, opts...).ToFunc()
}

// BySSHPassword orders the results by the ssh_password field.
func BySSHPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHPassword, opts...).ToFunc()
}

// BySSHAddress orders the results by the ssh_address field.
func BySSHAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHAddress, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByStoppedAt orders the results by the stopped_at field.
func ByStoppedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoppedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByChallengeField orders the results by challenge field.
func ByChallengeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChallengeStep(), sql.OrderByField(field, opts...))
	}
}

// ByCompetitionField orders the results by competition field.
func ByCompetitionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCompetitionStep(), sql.OrderByField(field, opts...))
	}
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}
func newChallengeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChallengeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChallengeTable, ChallengeColumn),
	)
}
func newCompetitionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CompetitionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CompetitionTable, CompetitionColumn),
	)
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
	)
}
